<script setup>
import {computed,nextTick,ref,watch} from 'vue';
import {activeTab,apiFetch,setActivePanelTab} from './store.js';
import {useClusterWorkspaces,clusterHistoryTrash,selectedClusterWorkspaceId,refreshClusterWorkspaces,notifyClusterDataChanged} from './cluster-workspace-store.mjs';
import {testPackageSummaries,testPackageMilestoneBuckets,refreshTestPackageSummaries} from './test-packages-store.mjs';
import {historyGroups} from './cluster-history.mjs';
import ClusterEvidenceHistory from './ClusterEvidenceHistory.vue';
import ClusterWorkspaceCard from './ClusterWorkspaceCard.vue';
const {clusterWorkspaces,clusterWorkspaceError}=useClusterWorkspaces();
const purge=ref(null);
const query=ref(''),trash=ref(false),expanded=ref(''),editing=ref(null),busy=ref(false),error=ref(''),notice=ref('');
const retained=computed(()=>clusterWorkspaces.value.filter(item=>item.archived));
const groups=computed(()=>historyGroups(trash.value?clusterHistoryTrash.value:retained.value,testPackageSummaries.value,testPackageMilestoneBuckets.value,query.value));
watch(activeTab,tab=>{if(tab==='history')refreshTestPackageSummaries().catch(err=>{error.value=err.message;});},{immediate:true});
watch([selectedClusterWorkspaceId,activeTab,()=>retained.value.map(item=>item.id).join(',')],async([id,tab])=>{
 if(tab!=='history'||!id)return;trash.value=false;query.value='';expanded.value=id;await nextTick();
 const element=[...document.querySelectorAll('[data-history-id]')].find(el=>el.dataset.historyId===id);
 if(element){element.scrollIntoView({block:'start'});element.focus({preventScroll:true});selectedClusterWorkspaceId.value='';}
},{flush:'post',immediate:true});
function edit(record){editing.value={id:record?.id||'',name:record?.nickname||record?.name||'',version:record?.version||'',milestone:record?.milestone||'',notes:record?.notes||''};error.value='';}
async function mutate(action,fields){if(busy.value)return;busy.value=true;error.value='';notice.value='';try{const response=await apiFetch('/api/cluster-workspaces',{method:'POST',body:JSON.stringify({action,...fields})});if(!response.ok)throw new Error(await response.text());await refreshClusterWorkspaces({fresh:true});notifyClusterDataChanged();editing.value=null;purge.value=null;notice.value=action==='purge'?'History permanently deleted. Independently saved lab and package records remain in their own libraries.':action==='delete'?'Moved to Trash. Linked lab records and package evidence are preserved.':action==='restore'?'History restored.':'History saved.';}catch(err){error.value=err.message;}finally{busy.value=false;}}
</script>
<template>
 <div class="history-page">
  <header><div><p class="history-eyebrow">RANCHER RUNWAY / SAVED WORK</p><h2>Retained History</h2><p>Removed clusters and their saved tests, snapshots, and packages. Grouped by milestone, then by Rancher version when no milestone is known.</p></div><button type="button" @click="setActivePanelTab('clusters')">← Live clusters</button></header>
  <div class="history-toolbar"><label>Search history<input v-model="query" type="search" placeholder="Milestone, version, cluster, run, notes…"></label><button type="button" :aria-pressed="!trash" @click="trash=false">History · {{retained.length}}</button><button type="button" :aria-pressed="trash" @click="trash=true">Trash · {{clusterHistoryTrash.length}}</button><button type="button" @click="edit(null)">Add history entry</button></div>
  <p v-if="error||clusterWorkspaceError" role="alert" class="history-error">{{error||clusterWorkspaceError}}</p><p v-if="notice" role="status">{{notice}}</p>
  <p v-if="trash">Trash removes the workspace card from History. Restore it to browse its linked work again. Test Lab, Cache Lab, and Test Packages keep their own records.</p>
  <form v-if="editing" class="history-editor" @submit.prevent="mutate(editing.id?'update':'create',editing)"><h3>{{editing.id?'Edit history':'Add a history entry'}}</h3><div class="history-fields"><label>Name<input v-model.trim="editing.name" required maxlength="160"></label><label>Milestone<input v-model.trim="editing.milestone" maxlength="160" placeholder="e.g. v2.16.0 — optional"></label><label>Rancher version<input v-model.trim="editing.version" maxlength="160" placeholder="e.g. v2.15.3-head"></label></div><label>Notes<textarea v-model="editing.notes" rows="3" maxlength="16384"></textarea></label><button type="submit" :disabled="busy||!editing.name">Save history</button> <button type="button" :disabled="busy" @click="editing=null">Cancel</button></form>
  <form v-if="purge" class="history-editor" @submit.prevent="mutate('purge',purge)"><h3>Permanently delete this environment archive?</h3><p>This cannot be undone. Deletes the history card, observed deployment details, saved commands, and upgrade/downstream operation records for this cluster. Independently saved Test Lab, Cache Lab, and Test Package evidence remains in those libraries.</p><p>Cluster ID: <code>{{purge.id}}</code></p><label>Type the exact cluster ID<input v-model="purge.confirmId" autocomplete="off" :disabled="busy"></label><label>Type DELETE PERMANENTLY<input v-model="purge.confirmPhrase" autocomplete="off" :disabled="busy"></label><button type="submit" :disabled="busy||purge.confirmId!==purge.id||purge.confirmPhrase!=='DELETE PERMANENTLY'">Permanently delete archive</button> <button type="button" :disabled="busy" @click="purge=null">Cancel</button></form>
  <p v-if="!groups.length" class="history-empty">{{query?'No matching history.':trash?'Trash is empty.':'No retained history yet. Removed cluster workspaces appear here automatically.'}}</p>
  <section v-for="group in groups" :key="group.label" class="history-group"><h3>{{group.label}} <small>{{group.clusters.length}}</small></h3>
   <article v-for="cluster in group.clusters" :key="cluster.id" :data-history-id="cluster.id" tabindex="-1" class="history-entry">
    <div class="history-entry-heading"><button v-if="!trash" type="button" class="history-expand" :aria-expanded="expanded===cluster.id" @click="expanded=expanded===cluster.id?'':cluster.id"><strong>{{cluster.nickname||cluster.name||cluster.id}}</strong><span>{{cluster.version||'Version not recorded'}} · {{cluster.runId?`Run ${cluster.runId}`:cluster.id}}</span><small>{{cluster.testRuns?.length||0}} test runs · {{cluster.testPlans?.length||0}} plans · {{cluster.snapshots?.length||0}} snapshots · {{expanded===cluster.id?'Hide saved work':'View saved work ↓'}}</small></button><div v-else><strong>{{cluster.nickname||cluster.name||cluster.id}}</strong><p>{{cluster.version||'Version not recorded'}}</p></div><div class="history-actions"><template v-if="!trash"><button type="button" :disabled="busy" @click="edit(cluster)">Edit</button><button type="button" :disabled="busy" @click="mutate('delete',{id:cluster.id})">Move to Trash</button></template><template v-else><button type="button" :disabled="busy" @click="mutate('restore',{id:cluster.id})">Restore</button><button type="button" :disabled="busy" @click="purge={id:cluster.id,confirmId:'',confirmPhrase:''}">Delete permanently</button></template></div></div>
    <p v-if="cluster.notes" class="history-notes">{{cluster.notes}}</p>
    <ClusterEvidenceHistory v-if="!trash&&expanded===cluster.id" :cluster-id="cluster.id"/>
    <ClusterWorkspaceCard v-if="!trash&&expanded===cluster.id" :cluster="cluster" />
   </article>
  </section>
 </div>
</template>
<style scoped>
.history-page{color:var(--runway-ink);font-size:13px;line-height:1.6}.history-page header,.history-toolbar,.history-entry-heading,.history-actions{display:flex;align-items:center;justify-content:space-between;gap:12px;flex-wrap:wrap}.history-page header{align-items:flex-start;margin-bottom:24px}.history-page h2{font-size:30px;font-weight:700;letter-spacing:-.03em}.history-eyebrow{font-size:10px;letter-spacing:.15em;color:var(--runway-accent)}.history-page p{margin:8px 0;color:var(--runway-muted)}.history-page button{cursor:pointer;border:1px solid var(--runway-border);border-radius:8px;padding:8px 12px;background:var(--runway-raised);color:var(--runway-ink);font:inherit;font-weight:600}.history-page button[aria-pressed=true]{color:var(--runway-accent);border-color:var(--runway-accent)}.history-page button:disabled{opacity:.5;cursor:not-allowed}.history-page label{display:grid;gap:5px}.history-toolbar>label{flex:1;min-width:220px}.history-page input,.history-page textarea{width:100%;border:1px solid var(--runway-border);background:var(--runway-card);color:var(--runway-ink);border-radius:8px;padding:9px;font:inherit}.history-editor,.history-entry{margin:14px 0;padding:18px;background:var(--runway-card);border:1px solid var(--runway-border);border-radius:14px;scroll-margin-top:130px}.history-fields{display:grid;grid-template-columns:repeat(auto-fit,minmax(200px,1fr));gap:12px;margin:12px 0}.history-editor>label{margin-bottom:12px}.history-group{margin-top:28px}.history-group h3{font-size:16px;font-weight:650}.history-group h3 small{color:var(--runway-muted);margin-left:8px}.history-entry-heading{flex-wrap:nowrap;align-items:start}.history-expand{display:grid;gap:5px;text-align:left;flex:1;min-width:0;border:0!important;background:transparent!important;padding:0!important}.history-expand strong{font-size:16px;overflow-wrap:anywhere}.history-expand span,.history-expand small{font-size:11px;color:var(--runway-muted);font-weight:400;overflow-wrap:anywhere}.history-notes{white-space:pre-wrap;overflow-wrap:anywhere}.history-error{color:var(--runway-error)!important}.history-empty{padding:35px;text-align:center}.history-page :focus-visible{outline:2px solid var(--runway-accent);outline-offset:3px}@media(max-width:650px){.history-entry-heading{flex-direction:column}.history-actions{justify-content:flex-start}}
</style>
