<script setup>
import {homeLayouts} from './home-layout.mjs';
import {homeLayout,homeLayoutError,setHomeLayout} from './home-preferences.mjs';
import Icon from './HelmLabIcon.vue';
defineProps({name:{type:String,default:'home-layout'}});
</script>
<template><fieldset class="home-layout-picker"><legend>Make Home yours</legend><p>Choose what you see first. Change it whenever your day changes.</p><div class="layout-options"><label v-for="layout in homeLayouts" :key="layout.id" :class="{selected:homeLayout===layout.id}"><input type="radio" :name="name" :value="layout.id" :checked="homeLayout===layout.id" @change="setHomeLayout(layout.id)"/><div class="layout-preview" :data-layout="layout.id" aria-hidden="true"><i></i><i></i><i></i><i></i></div><strong><Icon :name="layout.icon"/>{{layout.title}}</strong><span>{{layout.description}}</span></label></div><p v-if="homeLayoutError" role="status">{{homeLayoutError}}</p></fieldset></template>
<style scoped>
.home-layout-picker{border:0;color:var(--runway-ink);min-width:0}.home-layout-picker legend{font-size:16px;font-weight:650;letter-spacing:-.02em}.home-layout-picker>p{color:var(--runway-muted);font-size:12px;line-height:1.6;margin:6px 0 18px}.layout-options{display:grid;grid-template-columns:1fr 1fr;gap:14px}.layout-options label{position:relative;display:flex;flex-direction:column;gap:10px;border:1px solid var(--runway-border);border-radius:12px;background:var(--runway-card);padding:18px;cursor:pointer;transition:border-color 150ms,background 150ms}.layout-options label.selected{border-color:var(--runway-accent);background:var(--runway-accent-soft)}.layout-options input{position:absolute;right:15px;top:15px;accent-color:var(--runway-accent)}.layout-options label:focus-within{outline:2px solid var(--runway-accent);outline-offset:3px}.layout-options strong{display:flex;align-items:center;gap:8px;font-size:13px}.layout-options strong svg{width:16px;height:16px}.layout-options label>span{font-size:12px;line-height:1.65;color:var(--runway-muted)}.layout-preview{height:54px;width:110px;display:grid;grid-template-columns:2fr 1fr;gap:5px;margin-bottom:4px}.layout-preview i{border:1px solid var(--runway-border);border-radius:4px;background:var(--runway-soft)}.layout-preview i:first-child{grid-row:span 3;border-color:color-mix(in srgb,var(--runway-accent) 50%,var(--runway-border));background:var(--runway-accent-soft)}.layout-preview[data-layout=ready]{grid-template-columns:1fr 1fr 1fr}.layout-preview[data-layout=ready] i:first-child{grid-row:auto}.layout-preview[data-layout=ready] i:last-child{grid-column:span 3}@media(max-width:550px){.layout-options{grid-template-columns:1fr}}@media(prefers-reduced-motion:reduce){.layout-options label{transition:none}}
</style>
