<script setup>
import {computed} from 'vue';
import Icon from './HelmLabIcon.vue';
import ReadinessWorkflow from './ReadinessWorkflow.vue';
const props=defineProps({report:{type:Object,required:true}});
const qaLabel=computed(()=>({found:'QA template found on GitHub',draft:'QA template found on GitHub · needs details',not_found:'No QA template found on GitHub',unknown:'QA template check incomplete',not_required:'QA not required · QA/None'}[props.report.qa?.state]||'QA template check incomplete'));
const safeLink=url=>{try{const u=new URL(url);return u.protocol==='https:'&&u.hostname==='github.com'&&!u.username&&!u.password;}catch{return false;}};
const prState=pr=>pr.error?`Lookup failed: ${pr.error}`:pr.pull.merged?'Merged':pr.pull.draft&&pr.pull.state==='open'?'Draft · open':pr.pull.state==='closed'?'Closed without merging':'Open';
const verdict=match=>match?.verdict?.replaceAll('_',' ')||'unknown';
</script>
<template><div class="readiness-report" :data-green-light="!!report.workflow?.greenLight"><header><h2>{{report.title}}</h2><p>{{report.detail}}</p><p class="readiness-recommendation">{{report.recommendation}}</p><small>Checked {{new Date(report.checkedAt).toLocaleString()}} · {{report.platform}} · {{report.searchScope}}</small></header>
   <template v-if="report"><ReadinessWorkflow :workflow="report.workflow" :statuses="report.statuses" :build-available="report.verdict==='ready'"/>
    <div class="readiness-issue-state"><strong>GitHub issue</strong><span>{{report.issue.state}}{{report.issue.state_reason?` · ${report.issue.state_reason}`:''}}</span><span v-if="report.issue.milestone">Milestone {{report.issue.milestone.title}}</span><span v-if="report.issue.assignees?.length">{{report.issue.assignees.map(owner=>'@'+owner.login).join(', ')}}</span><div v-if="report.issue.labels?.length" class="readiness-labels"><span v-for="label in report.issue.labels" :key="label.name">{{label.name}}</span></div></div>
    
    <section class="qa-template" :data-qa="report.qa?.state"><h3>{{qaLabel}}</h3><p v-if="report.qa?.state==='not_found'"><strong>Action needed:</strong> No QA template was found in the issue description or scanned comments. Request testing guidance before validation.</p><p v-else-if="report.qa?.state==='draft'"><strong>Action needed:</strong> A QA template exists, but its detected sections are blank.</p><p>GitHub guidance and saved Runway test cases are tracked separately.</p><p v-if="!report.qa?.complete">Comment scanning was incomplete; additional templates may exist.</p><article v-for="template in report.qa?.templates||[]" :key="template.url"><a v-if="safeLink(template.url)" :href="template.url" target="_blank" rel="noopener noreferrer">Open QA template on GitHub ↗</a><span>{{template.author?' · @'+template.author:''}} · {{template.hasContent?'Contains guidance':'Needs details'}}</span><details><summary>View detected sections</summary><section v-for="(section,index) in template.sections" :key="index"><strong>{{section.name}}</strong><p class="qa-copy">{{section.text||'Not filled in'}}</p></section><p v-if="template.truncated">Preview shortened. Open the GitHub comment for the full template.</p></details></article></section>
    <div v-if="report.prs.length" class="readiness-prs"><strong>Linked pull requests · {{report.prs.length}}</strong><article v-for="pr in report.prs" :key="pr.pull.url"><a :href="pr.pull.url" target="_blank" rel="noopener noreferrer">{{pr.pull.repository}}#{{pr.pull.number}} · {{pr.pull.title||'Pull request'}}</a><span>{{prState(pr)}} · {{pr.relationship==='declared_fix'?'Issue declared in PR description':pr.relationship}}</span><small v-if="pr.pull.baseRef">{{pr.pull.headRef}} → {{pr.pull.baseRef}}</small><small v-if="pr.backportOf?.length">Declared backport of <a v-for="url in pr.backportOf" :key="url" :href="url" target="_blank" rel="noopener noreferrer">{{url.replace('https://github.com/','').replace('/pull/','#')}}</a></small></article></div>
    <div v-if="report.builds.length" class="readiness-builds"><strong>Observed head builds<span v-if="report.targetLine"> · target {{report.targetLine}}</span></strong><article v-for="(build,index) in report.builds" :key="`${build.registry}-${build.tag}-${index}`" :data-ready="build.ready"><div><strong>{{build.label}} · {{build.tag}}</strong><span>{{build.includedFixes}} / {{build.requiredFixes}} required fixes proven{{build.ready?' · build available':''}}</span></div><details><summary>Image and PR evidence</summary><p><b>Server:</b> {{build.server.found?build.server.reference:'Not found'}}<span v-if="build.server.error"> · {{build.server.error}}</span></p><code v-if="build.server.platformDigest">{{build.server.platformDigest}}</code><p><b>Agent:</b> {{build.agent.found?build.agent.reference:'Not found'}}<span v-if="build.agent.error"> · {{build.agent.error}}</span></p><code v-if="build.agent.platformDigest">{{build.agent.platformDigest}}</code><ul><li v-for="match in build.matches" :key="match.pr"><a :href="match.pr" target="_blank" rel="noopener noreferrer">{{match.pr.replace('https://github.com/','').replace('/pull/','#')}}</a> · server {{verdict(match.server)}} / agent {{verdict(match.agent)}}<p>{{match.server.reason}} {{match.agent.reason!==match.server.reason?match.agent.reason:''}}</p><a v-if="safeLink(match.server.evidenceUrl)" :href="match.server.evidenceUrl" target="_blank" rel="noopener noreferrer">Rancher dependency pin ↗</a> <a v-if="safeLink(match.agent.evidenceUrl)&&match.agent.evidenceUrl!==match.server.evidenceUrl" :href="match.agent.evidenceUrl" target="_blank" rel="noopener noreferrer">Agent dependency pin ↗</a> <a v-if="safeLink(match.server.chartUrl)" :href="match.server.chartUrl" target="_blank" rel="noopener noreferrer">Webhook chart defaults ↗</a><code v-if="match.server.componentImage">{{match.server.componentImage}} · {{match.server.componentDigest}}</code><a v-if="safeLink(match.server.compareUrl)" :href="match.server.compareUrl" target="_blank" rel="noopener noreferrer">Server ancestry</a> <a v-if="safeLink(match.agent.compareUrl)" :href="match.agent.compareUrl" target="_blank" rel="noopener noreferrer">Agent ancestry</a></li></ul></details></article></div>
    <ul v-if="report.warnings.length" class="readiness-warnings"><li v-for="warning in report.warnings" :key="warning">{{warning}}</li></ul>
    <p v-if="!report.complete" class="readiness-incomplete"><Icon name="signal"/>Some evidence is unavailable. Any build marked available has proof for its required fixes; other results remain unknown.</p>
   </template>
</div></template>
<style scoped>
.readiness-report[data-green-light=true]>header h2{color:var(--runway-accent,#16735e)}.readiness{min-width:0}.readiness.compact .readiness-trigger{font-size:10px;padding:6px 8px}.readiness-trigger{display:inline-flex;align-items:center;gap:7px;padding:7px 10px;border:1px solid var(--runway-border,#dfe7e4);border-radius:8px;background:var(--runway-card,#fff);color:var(--runway-accent,#16735e);font-size:11px;font-weight:650;cursor:pointer}.readiness-trigger svg{width:15px;height:15px}.readiness-trigger:disabled{opacity:.6;cursor:wait}.readiness-report{margin-top:12px;padding:16px;border:1px solid var(--runway-border,#dfe7e4);border-radius:13px;background:var(--runway-card,#fff);color:var(--runway-ink,#203230);font-size:11px;line-height:1.65}.readiness-report header>div{display:flex;align-items:center;justify-content:space-between}.readiness-eyebrow{font-size:9px;letter-spacing:.12em;text-transform:uppercase;color:var(--runway-muted,#657577)}.readiness-close{display:grid;place-items:center;border:0;background:none;color:inherit;cursor:pointer}.readiness-close svg{width:15px;height:15px}.readiness-report h3{font-size:17px;line-height:1.35;margin:7px 0}.readiness-report p{margin:5px 0}.readiness-recommendation{padding:9px 11px;border-radius:8px;background:var(--runway-accent-soft,#e8f3ef)}.readiness-wait{display:flex;gap:8px;align-items:center;padding:10px 0;color:var(--runway-muted,#657577)}.readiness-issue-state,.readiness-statuses,.readiness-prs,.readiness-builds{display:grid;gap:7px;margin-top:14px;padding-top:12px;border-top:1px solid var(--runway-border,#dfe7e4)}.readiness-issue-state>span,.readiness-statuses>span{color:var(--runway-muted,#657577)}.readiness-labels{display:flex;gap:5px;flex-wrap:wrap}.readiness-labels span{padding:2px 6px;border-radius:5px;background:var(--runway-accent-soft,#e8f3ef);font-size:9px}.readiness-prs article,.readiness-builds article{display:grid;gap:3px;padding:9px 10px;border:1px solid var(--runway-border,#dfe7e4);border-radius:8px;overflow-wrap:anywhere}.readiness-prs a,.readiness-builds a{color:var(--runway-accent,#16735e);text-decoration:underline;text-underline-offset:2px}.readiness-prs span,.readiness-prs small{color:var(--runway-muted,#657577)}.readiness-builds article[data-ready=true]{border-color:#319476;background:#3194760b}.readiness-builds article>div{display:flex;justify-content:space-between;gap:12px;flex-wrap:wrap}.readiness-builds article>div span{color:var(--runway-muted,#657577)}.readiness-builds details{color:var(--runway-muted,#657577)}.readiness-builds summary{cursor:pointer}.readiness-builds ul{padding-left:18px}.readiness-warnings{margin:12px 0;padding-left:18px;color:#986b14}.readiness-incomplete{display:flex;align-items:center;gap:7px;color:#986b14}.readiness-incomplete svg{width:14px;height:14px}.spin{animation:spin 1.2s linear infinite}@keyframes spin{to{transform:rotate(360deg)}}
.qa-template[data-qa=not_found],.qa-template[data-qa=draft]{padding:15px;border:1px solid #c08a2070;border-radius:10px;background:#c08a2012}.qa-template{border-top:1px solid var(--runway-border);margin-top:18px;padding-top:14px}.qa-template h3{font-size:15px}.qa-template article{margin-top:12px}.qa-template a{color:var(--runway-accent);text-decoration:underline}.qa-template details{margin-top:10px}.qa-template details section{padding:8px 0}.qa-copy{white-space:pre-wrap;overflow-wrap:anywhere}.readiness-report code{display:block;overflow-wrap:anywhere;font-size:10px}.readiness-report h2{font-size:23px;font-weight:650;margin:5px 0 12px}.readiness-report small{color:var(--runway-muted)}
</style>
