<script setup>
import {ref,watch,nextTick,onBeforeUnmount} from 'vue';
import {readinessDialogOpen,readinessResult,closeIssueReadiness,openIssueReadiness} from './issue-readiness-store.mjs';
import ReadinessProgress from './ReadinessProgress.vue';
import Report from './IssueReadinessReport.vue';
const dialog=ref(null);
watch(readinessDialogOpen,async open=>{await nextTick();if(open&&!dialog.value?.open)dialog.value?.showModal();else if(!open&&dialog.value?.open)dialog.value.close();});
onBeforeUnmount(closeIssueReadiness);
</script>
<template><Teleport to="body"><dialog ref="dialog" class="readiness-dialog" aria-labelledby="readiness-dialog-title" @cancel.prevent="closeIssueReadiness" @click="event=>{if(event.target===dialog)closeIssueReadiness();}"><div class="readiness-dialog-top"><div><small>ISSUE READINESS</small><h2 id="readiness-dialog-title">{{readinessResult.report?.issue.title||readinessResult.issueUrl}}</h2></div><button type="button" autofocus @click="closeIssueReadiness">{{readinessResult.busy?'Cancel scan':'Close'}}</button></div><ReadinessProgress v-if="readinessResult.busy" :progress="readinessResult.progress" :started-at="readinessResult.startedAt"/><p v-if="readinessResult.error" role="alert">{{readinessResult.error}}</p><Report v-if="readinessResult.report" :report="readinessResult.report"/><footer v-if="!readinessResult.busy" class="readiness-actions"><button type="button" class="readiness-again" @click="openIssueReadiness(readinessResult.issueUrl)">Check again</button><button v-if="readinessResult.report && !readinessResult.busy && readinessResult.report.verdict!=='qa_not_required'" type="button" class="readiness-again" @click="openIssueReadiness(readinessResult.issueUrl,{expanded:true})">Search other release heads</button></footer></dialog></Teleport></template>
<style scoped>.readiness-dialog{width:min(880px,calc(100vw - 32px));max-height:88vh;overflow:auto;border:1px solid var(--runway-border,#dfe7e4);border-radius:20px;padding:24px;background:var(--runway-card,#fff);color:var(--runway-ink,#203230);box-shadow:0 24px 90px #0004}.readiness-dialog::backdrop{background:#071c24a6}.readiness-dialog-top{display:flex;gap:20px;justify-content:space-between;align-items:flex-start}.readiness-dialog-top h2{font-size:18px;overflow-wrap:anywhere;font-weight:650;margin-top:6px}.readiness-dialog small{font-size:10px;letter-spacing:.13em;color:var(--runway-muted)}.readiness-dialog button{flex-shrink:0;border:1px solid var(--runway-border,#dfe7e4);border-radius:8px;background:var(--runway-raised,#fff);color:inherit;padding:9px 12px;cursor:pointer;font-size:12px}.readiness-loading{padding:35px 0;line-height:1.8}.readiness-actions{display:flex;flex-wrap:wrap;gap:12px;margin-top:22px;padding-top:18px;border-top:1px solid var(--runway-border,#dfe7e4)}.readiness-actions button{min-height:42px;padding:11px 16px}.readiness-actions button:first-child{border-color:var(--runway-accent,#319476)}@media(max-width:520px){.readiness-actions button{flex:1 1 100%;white-space:normal}}.readiness-dialog :focus-visible{outline:2px solid var(--runway-accent);outline-offset:3px}</style>
