<script setup>
import {computed,nextTick,ref,watch} from 'vue';
import Icon from './HelmLabIcon.vue';
import {CASE_OUTCOMES,packageDate} from './issue-packages.mjs';
import {caseStepProgress,changedCaseFields,evidenceForCase,nextCaseToCheck,outcomeLabel,resultForCase} from './issue-package-comparison.mjs';

const props=defineProps({session:{type:Object,required:true},caseId:String,observation:{type:String,default:''},busy:Boolean,observationBlocked:Boolean,baseline:Object});
const emit=defineEmits(['select-case','update:observation','mark-step','outcome','save-observation','logs','attach-evidence','run-automation']);
const heading=ref(null),expandedBaseline=ref(false);
const cases=computed(()=>props.session.cases||[]);
const activeCase=computed(()=>cases.value.find(item=>item.id===props.caseId));
const activeIndex=computed(()=>cases.value.findIndex(item=>item.id===props.caseId));
const result=computed(()=>resultForCase(props.session,props.caseId));
const baselineRecord=computed(()=>props.baseline||props.session.baseline);
const baselineCase=computed(()=>baselineRecord.value?.cases?.find(item=>item.id===props.caseId));
const baselineResult=computed(()=>resultForCase(baselineRecord.value,props.caseId));
const baselineChanges=computed(()=>changedCaseFields(baselineCase.value,activeCase.value));
const baselineNotes=computed(()=>baselineResult.value?.notes||'No case observation was recorded in the baseline.');
const baselineEvidence=computed(()=>evidenceForCase(baselineRecord.value,props.caseId));
const evidence=computed(()=>evidenceForCase(props.session,props.caseId));
const nextCase=computed(()=>nextCaseToCheck(props.session,props.caseId));
const stepProgress=computed(()=>caseStepProgress(activeCase.value,result.value));
const active=computed(()=>props.session.status==='active');
const unrun=computed(()=>cases.value.filter(item=>(resultForCase(props.session,item.id)?.outcome||'not-run')==='not-run').length);
const stepMarker=id=>result.value?.steps?.find(item=>item.stepId===id);
watch(()=>[props.session.id,props.caseId],()=>{expandedBaseline.value=false;});
async function advance(){if(!nextCase.value||props.busy)return;emit('select-case',nextCase.value.id);await nextTick();heading.value?.focus({preventScroll:true});}
</script>

<template>
  <section class="package-execution" aria-label="Case execution">
    <div v-if="activeCase?.automationSource" class="px-automation"><div><strong>{{activeCase.automationSource.name}}</strong><small>rancher/tests@{{activeCase.automationSource.sha.slice(0,12)}} · {{activeCase.selection.length}} selections</small></div><button v-if="active" type="button" :disabled="busy" @click="$emit('run-automation',caseId)"><Icon name="play"/>Review & run in Test Lab</button><p>Finished results and logs are copied to this case. Review them before recording an outcome.</p></div><div class="px-toolbar">
      <div><span class="px-eyebrow">{{active?'WORK THROUGH THE PLAN':'PRESERVED CASE RESULTS'}}</span><strong>{{unrun?`${unrun} ${unrun===1?'case still needs':'cases still need'} an outcome`:'Every case has a recorded outcome'}}</strong></div>
      <button v-if="active&&nextCase" type="button" class="px-next" :disabled="busy" :title="nextCase.title" @click="advance">{{nextCase.blocked?'Revisit a blocked case':'Next unrun case'}}<Icon name="arrow"/></button>
    </div>
    <div class="px-layout">
      <nav class="px-case-list" aria-label="Session cases">
        <button v-for="(item,index) in cases" :key="item.id" type="button" :class="{selected:caseId===item.id}" :aria-current="caseId===item.id?'step':undefined" :disabled="busy" @click="$emit('select-case',item.id)">
          <span class="px-case-number">{{String(index+1).padStart(2,'0')}}</span><span class="px-case-label"><strong>{{item.title}}</strong><small :data-outcome="resultForCase(session,item.id)?.outcome||'not-run'"><span class="px-dot"/>{{outcomeLabel(resultForCase(session,item.id)?.outcome)}}</small></span>
        </button>
      </nav>
      <div v-if="activeCase" class="px-workspace" :class="{'with-baseline':baselineRecord}">
        <article class="px-current-case">
          <header class="px-case-heading"><div><span class="px-eyebrow">CASE {{String(activeIndex+1).padStart(2,'0')}} OF {{cases.length}}</span><h4 ref="heading" tabindex="-1">{{activeCase.title}}</h4></div><span class="px-outcome" :data-outcome="result?.outcome||'not-run'">{{outcomeLabel(result?.outcome)}}</span></header>
          <div v-if="activeCase.preconditions" class="px-condition"><span class="px-eyebrow">BEFORE YOU BEGIN</span><p>{{activeCase.preconditions}}</p></div>
          <div v-if="activeCase.steps?.length" class="px-step-progress"><span>{{stepProgress.done}} of {{stepProgress.total}} steps marked performed</span><div aria-hidden="true"><span :style="{width:`${stepProgress.total?stepProgress.done/stepProgress.total*100:0}%`}"/></div></div>
          <ol v-if="activeCase.steps?.length" class="px-steps">
            <li v-for="(step,index) in activeCase.steps" :key="step.id" class="px-step" :class="{done:stepMarker(step.id)?.done}">
              <label><input type="checkbox" :checked="!!stepMarker(step.id)?.done" :disabled="!active||busy" :aria-label="`Mark step ${index+1} performed: ${step.instruction}`" @change="$emit('mark-step',{step,done:$event.target.checked})"/><span><small>STEP {{String(index+1).padStart(2,'0')}}</small><strong>{{step.instruction}}</strong></span></label>
              <p v-if="step.expected"><span>Expect</span>{{step.expected}}</p>
              <div class="px-step-footer"><time v-if="stepMarker(step.id)?.done">Performed {{packageDate(stepMarker(step.id).at,true)}}</time><button v-if="active&&session.environment?.clusterId" type="button" class="px-link" :disabled="busy" :aria-label="`Capture logs for step ${index+1}`" @click="$emit('logs',{caseId:activeCase.id,stepId:step.id})"><Icon name="terminal"/>Capture logs</button></div>
            </li>
          </ol>
          <div v-if="activeCase.expected" class="px-condition px-expected"><Icon name="compass"/><div><span class="px-eyebrow">EXPECTED BEHAVIOR</span><p>{{activeCase.expected}}</p></div></div>
          <div class="px-observation">
            <label :for="`package-observation-${session.id}-${activeCase.id}`">What happened?</label><p v-if="active" class="px-hint">Record the behavior you saw, then choose an outcome. Step markers alone do not mark a case passed.</p>
            <textarea v-if="active" :id="`package-observation-${session.id}-${activeCase.id}`" :value="observation" :disabled="busy||observationBlocked" rows="5" placeholder="Actual behavior, anything unexpected, and what this result establishes…" @input="$emit('update:observation',$event.target.value)"/>
            <p v-else class="px-preserved-note">{{result?.notes||'No observation recorded.'}}</p>
            <p v-if="observationBlocked" class="px-baseline-warning">A recovered observation needs review above. Choose which text to keep before saving this case’s result.</p><div v-if="active" class="px-observation-state"><span>{{observation!==(result?.notes||'')?'Draft · choose an outcome or save this observation':'Observation saved with this case'}}</span><button type="button" class="px-link" :disabled="busy||observationBlocked||observation===(result?.notes||'')" @click="$emit('save-observation')">Save observation</button></div>
            <div v-if="active" class="px-outcomes" role="group" aria-label="Record case outcome"><button v-for="item in CASE_OUTCOMES.filter(item=>item.id!=='not-run')" :key="item.id" type="button" :data-outcome="item.id" :aria-pressed="result?.outcome===item.id" :disabled="busy||observationBlocked" @click="$emit('outcome',item.id)"><Icon v-if="result?.outcome===item.id" name="check"/>{{item.label}}</button></div>
          </div>
          <section class="px-case-evidence" aria-label="Evidence for this case"><header><div><Icon name="layers"/><strong>{{evidence.length?`${evidence.length} ${evidence.length===1?'record':'records'} attached to this case`:'Evidence for this case'}}</strong></div><div v-if="active" class="px-evidence-actions"><button v-if="session.environment?.clusterId" type="button" class="px-link" :disabled="busy" @click="$emit('logs',{caseId:activeCase.id,stepId:''})"><Icon name="terminal"/>Get logs</button><button type="button" class="px-link" :disabled="busy" @click="$emit('attach-evidence',{caseId:activeCase.id})"><Icon name="plus"/>Attach evidence</button></div></header><ul v-if="evidence.length"><li v-for="item in evidence" :key="item.id"><Icon :name="item.kind==='pod-logs'?'terminal':item.kind==='cache-snapshot'?'database':'file'"/><span>{{item.name||'Written observation'}}<small v-if="item.stepId">Step {{(activeCase.steps||[]).findIndex(step=>step.id===item.stepId)+1}}</small></span></li></ul><p v-else class="px-hint">Attach a lab result, cache snapshot, log capture, or written observation. Session-wide evidence stays below.</p></section>
          <footer v-if="active" class="px-case-footer"><span v-if="nextCase">{{nextCase.blocked?'A blocked case is ready to revisit.':'Continue when you are ready. Your observation stays with this case.'}}</span><span v-else>{{unrun?'This is the last unrun case.':'No other unrun or blocked cases.'}}</span><button v-if="nextCase" type="button" :disabled="busy" @click="advance">{{nextCase.blocked?'Review blocked case':'Next unrun case'}}<Icon name="arrow"/></button></footer>
        </article>
        <aside v-if="baselineRecord" class="px-baseline" aria-label="Baseline observations for this case">
          <div class="px-baseline-heading"><span class="px-baseline-icon"><Icon name="bookmark"/></span><div><span class="px-eyebrow">PREVIOUS OBSERVATION</span><h5>{{baselineRecord.name||'Preserved baseline'}}</h5></div></div>
          <p class="px-baseline-version">Rancher {{baselineRecord.environment?.rancherVersion||'version not recorded'}}</p>
          <template v-if="baselineCase"><span class="px-outcome" :data-outcome="baselineResult?.outcome||'not-run'">{{outcomeLabel(baselineResult?.outcome)}}</span><p v-if="baselineChanges.length" class="px-baseline-warning"><Icon name="signal"/>Case content differs: {{baselineChanges.join(', ')}}. Treat the outcomes as separate observations.</p><p v-else class="px-baseline-match"><Icon name="check"/>Same case and steps</p><p class="px-baseline-notes">{{expandedBaseline||baselineNotes.length<=900?baselineNotes:baselineNotes.slice(0,900)+'…'}}</p><button v-if="baselineNotes.length>900" type="button" class="px-link" :aria-expanded="expandedBaseline" @click="expandedBaseline=!expandedBaseline">{{expandedBaseline?'Show less':'Read full observation'}}</button><details v-if="baselineEvidence.length" class="px-baseline-evidence"><summary>{{baselineEvidence.length}} baseline evidence {{baselineEvidence.length===1?'record':'records'}}<Icon name="chevron"/></summary><ul><li v-for="item in baselineEvidence" :key="item.id">{{item.name||'Written observation'}}</li></ul><p>Preserved references. Open the original session to inspect available attachments.</p></details></template>
          <p v-else class="px-baseline-warning">This case was not part of the preserved baseline. There is no earlier result to compare.</p>
          <div class="px-baseline-footer"><Icon name="lock"/><span>Captured with this validation session. Later edits or deletion of the original session do not change this reference.</span></div>
        </aside>
      </div>
      <p v-else class="px-empty">Choose a case to see its steps and observations.</p>
    </div>
  </section>
</template>

<style scoped>
.px-automation{display:flex;align-items:center;gap:12px;flex-wrap:wrap;border:1px solid var(--runway-border);border-radius:10px;padding:15px;margin-bottom:18px;background:var(--runway-accent-soft)}.px-automation>div{flex:1;min-width:160px}.px-automation strong{display:block;font-size:12px}.px-automation small{display:block;font:10px ui-monospace,monospace;margin-top:6px;color:var(--runway-muted);overflow-wrap:anywhere}.px-automation p{width:100%;margin:0;color:var(--runway-muted);font-size:11px;line-height:1.6}.px-automation button{display:flex;align-items:center;gap:7px;font:12px inherit;background:var(--runway-card);border:1px solid var(--runway-border);border-radius:8px;padding:10px;color:var(--runway-accent);cursor:pointer}.px-automation button:disabled{opacity:.4}.px-automation svg{width:14px;height:14px}

.package-execution{container:execution / inline-size;color:var(--runway-ink);border:1px solid var(--runway-border);border-radius:16px;overflow:hidden;margin:24px 0;background:var(--runway-card)}
.package-execution button{display:inline-flex;align-items:center;justify-content:center;gap:8px;border:1px solid var(--runway-border);border-radius:9px;background:var(--runway-input);color:var(--runway-ink);padding:10px 13px;font:inherit;font-size:12px;line-height:1.5;cursor:pointer;transition:background .15s,border-color .15s}
.package-execution button:hover:not(:disabled){background:var(--runway-raised);border-color:var(--runway-accent)}.package-execution button:disabled{opacity:.5;cursor:default}.package-execution :focus-visible{outline:2px solid var(--runway-accent);outline-offset:3px}.package-execution svg{width:16px;height:16px;flex-shrink:0}.package-execution .px-link{background:transparent;border:0;color:var(--runway-accent);padding:5px 0;font-size:11px}.package-execution .px-link:hover:not(:disabled){background:transparent;text-decoration:underline}.px-eyebrow{font-size:9px;line-height:1.5;font-weight:650;letter-spacing:.13em;color:var(--runway-muted)}
.px-toolbar{padding:19px 22px;display:flex;align-items:center;justify-content:space-between;gap:16px;border-bottom:1px solid var(--runway-border);background:var(--runway-soft)}.px-toolbar>div{display:grid;gap:5px}.px-toolbar strong{font-size:13px;font-weight:550}.package-execution .px-next{color:var(--runway-accent);flex-shrink:0}.px-layout{display:grid;grid-template-columns:210px minmax(0,1fr)}.px-case-list{padding:12px;display:flex;flex-direction:column;gap:5px;background:var(--runway-soft);border-right:1px solid var(--runway-border);align-self:stretch;max-height:760px;overflow:auto;scrollbar-gutter:stable}.package-execution .px-case-list button{text-align:left;align-items:flex-start;justify-content:flex-start;background:transparent;border-color:transparent;padding:13px 10px;gap:10px}.package-execution .px-case-list button.selected{background:var(--runway-accent-soft);box-shadow:inset 3px 0 var(--runway-accent);border-color:var(--runway-border)}.px-case-number{font:10px/1.6 ui-monospace,monospace;color:var(--runway-muted);padding-top:2px}.px-case-label{min-width:0;display:grid;gap:7px}.px-case-label strong{font-size:12px;line-height:1.6;font-weight:550;overflow-wrap:anywhere}.px-case-label small{display:flex;align-items:center;gap:5px;font-size:10px;color:var(--runway-muted)}.px-dot{width:5px;height:5px;flex-shrink:0;border-radius:50%;background:currentColor}.px-workspace{min-width:0;display:grid}.px-current-case{padding:26px;min-width:0}.px-case-heading{display:flex;justify-content:space-between;align-items:flex-start;gap:15px;margin-bottom:24px}.px-case-heading h4{font-size:19px;line-height:1.45;letter-spacing:-.025em;margin:8px 0 0;overflow-wrap:anywhere;font-weight:600}.px-outcome{display:inline-flex;align-items:center;width:max-content;border:1px solid var(--runway-border);border-radius:7px;background:var(--runway-soft);font-size:10px;font-weight:600;line-height:1.6;padding:4px 8px;white-space:nowrap;color:var(--runway-muted)}[data-outcome=passed]{color:var(--runway-accent)!important}[data-outcome=failed]{color:var(--runway-error)!important}[data-outcome=blocked]{color:var(--runway-gold)!important}
.px-condition{padding:15px 17px;border:1px solid var(--runway-border);border-radius:10px;background:var(--runway-soft);margin-bottom:22px}.px-condition p{white-space:pre-wrap;overflow-wrap:anywhere;font-size:12px;line-height:1.9;margin:7px 0 0}.px-expected{display:flex;align-items:flex-start;gap:12px;margin-top:20px}.px-expected>svg{color:var(--runway-accent);margin-top:1px}.px-step-progress{display:flex;align-items:center;gap:16px;font-size:10px;color:var(--runway-muted);margin-bottom:14px}.px-step-progress>div{flex:1;max-width:160px;height:3px;border-radius:10px;background:var(--runway-border);overflow:hidden}.px-step-progress>div>span{display:block;height:100%;background:var(--runway-accent);transition:width .2s}.px-steps{list-style:none;margin:0;padding:0;display:grid;gap:10px}.px-step{border:1px solid var(--runway-border);background:var(--runway-input);border-radius:12px;padding:17px 18px}.px-step.done{background:var(--runway-accent-soft)}.px-step label{display:flex;align-items:flex-start;gap:12px;cursor:pointer}.px-step input{appearance:auto;accent-color:var(--runway-accent);height:17px;width:17px;margin:2px 0 0;flex-shrink:0}.px-step label>span{display:grid;gap:7px;min-width:0}.px-step small{font:9px/1.5 ui-monospace,monospace;color:var(--runway-muted);letter-spacing:.09em}.px-step strong{font-size:13px;line-height:1.8;font-weight:550;white-space:pre-wrap;overflow-wrap:anywhere}.px-step>p{font-size:12px;line-height:1.85;color:var(--runway-muted);margin:12px 0 0 29px;white-space:pre-wrap;overflow-wrap:anywhere}.px-step>p>span{font-weight:600;font-size:10px;display:block;color:var(--runway-ink);margin-bottom:3px}.px-step-footer{display:flex;align-items:center;justify-content:space-between;gap:10px;margin-left:29px}.px-step-footer:not(:empty){margin-top:12px}.px-step-footer time{font-size:9px;line-height:1.7;color:var(--runway-muted)}.px-step-footer>.px-link{margin-left:auto}
.px-observation{margin-top:24px}.px-observation>label{display:block;font-weight:600;font-size:13px;margin-bottom:7px}.px-hint{color:var(--runway-muted);font-size:11px;line-height:1.8;margin:6px 0 12px}.px-observation textarea{box-sizing:border-box;display:block;width:100%;min-height:140px;resize:vertical;border:1px solid var(--runway-control);border-radius:11px;background:var(--runway-input);color:var(--runway-ink);padding:14px 16px;font-family:inherit;font-size:12px;line-height:1.9}.px-observation textarea::placeholder{color:var(--runway-muted)}.px-observation-state{display:flex;justify-content:space-between;align-items:center;gap:12px;min-height:37px;font-size:9px;line-height:1.7;color:var(--runway-muted)}.px-outcomes{display:flex;flex-wrap:wrap;gap:8px;margin-top:8px}.package-execution .px-outcomes button{flex:1;min-width:74px;background:var(--runway-soft);font-size:11px}.package-execution .px-outcomes button[aria-pressed=true]{border-color:currentColor;background:var(--runway-accent-soft)}.px-preserved-note{white-space:pre-wrap;overflow-wrap:anywhere;font-size:12px;line-height:1.9;margin:12px 0;padding:17px;border:1px solid var(--runway-border);border-radius:10px;background:var(--runway-soft)}
.px-case-evidence{margin-top:24px;padding-top:19px;border-top:1px solid var(--runway-border)}.px-case-evidence header{display:flex;flex-wrap:wrap;justify-content:space-between;gap:12px;align-items:center}.px-case-evidence header>div{display:flex;align-items:center;gap:9px}.px-case-evidence header>div>svg{color:var(--runway-accent)}.px-case-evidence strong{font-size:11px;font-weight:550}.px-case-evidence .px-evidence-actions{gap:14px}.px-case-evidence ul{list-style:none;margin:13px 0 0;padding:0;display:grid;gap:8px}.px-case-evidence li{display:flex;gap:8px;align-items:flex-start;font-size:11px;line-height:1.7;color:var(--runway-muted);overflow-wrap:anywhere}.px-case-evidence li>svg{margin-top:2px;width:13px;height:13px}.px-case-evidence li small{font-size:9px;border-left:1px solid var(--runway-border);padding-left:7px;margin-left:7px;white-space:nowrap}.px-case-evidence .px-hint{margin-top:12px}.px-case-footer{margin-top:24px;padding-top:20px;border-top:1px solid var(--runway-border);display:flex;justify-content:space-between;align-items:center;gap:15px}.px-case-footer>span{font-size:10px;line-height:1.8;color:var(--runway-muted)}.px-case-footer>button{flex-shrink:0;color:var(--runway-accent)}
.px-baseline{padding:23px;background:var(--runway-soft);border-bottom:1px solid var(--runway-border);min-width:0;order:-1}.px-baseline-heading{display:flex;align-items:flex-start;gap:10px}.px-baseline-icon{padding:8px;background:var(--runway-accent-soft);color:var(--runway-accent);border-radius:9px;display:grid;place-items:center}.px-baseline h5{font-size:12px;line-height:1.65;font-weight:600;margin:5px 0 0;overflow-wrap:anywhere}.px-baseline-version{color:var(--runway-muted);font-size:10px;line-height:1.7;margin:16px 0 11px;overflow-wrap:anywhere}.px-baseline-match,.px-baseline-warning{display:flex;align-items:flex-start;gap:7px;font-size:10px;line-height:1.8;margin:14px 0}.px-baseline-match{color:var(--runway-accent)}.px-baseline-warning{color:var(--runway-gold)}.px-baseline-match svg,.px-baseline-warning svg{width:13px;height:13px;margin-top:2px}.px-baseline-notes{font-size:12px;line-height:1.9;white-space:pre-wrap;overflow-wrap:anywhere;margin:15px 0 20px}.px-baseline-evidence{border-top:1px solid var(--runway-border);padding-top:14px;margin-top:20px}.px-baseline-evidence summary{display:flex;justify-content:space-between;align-items:center;gap:10px;list-style:none;font-size:10px;line-height:1.7;cursor:pointer}.px-baseline-evidence summary::-webkit-details-marker{display:none}.px-baseline-evidence[open] summary svg{transform:rotate(180deg)}.px-baseline-evidence ul{padding-left:17px;font-size:10px;line-height:1.8;color:var(--runway-muted)}.px-baseline-evidence li{margin:6px 0;overflow-wrap:anywhere}.px-baseline-evidence p{font-size:9px;line-height:1.8;color:var(--runway-muted)}.px-baseline-footer{display:flex;gap:8px;align-items:flex-start;border-top:1px solid var(--runway-border);padding-top:15px;margin-top:22px;font-size:9px;line-height:1.8;color:var(--runway-muted)}.px-baseline-footer svg{width:12px;height:12px;margin-top:2px}.px-empty{padding:25px;font-size:12px;color:var(--runway-muted)}
@container execution (min-width:1080px){.px-workspace.with-baseline{grid-template-columns:minmax(0,1fr) 260px}.px-baseline{order:0;border-bottom:0;border-left:1px solid var(--runway-border)}}
@container execution (max-width:740px){.px-layout{grid-template-columns:1fr}.px-case-list{flex-direction:row;border-right:0;border-bottom:1px solid var(--runway-border);max-height:none;padding:10px;gap:5px}.package-execution .px-case-list button{min-width:180px;max-width:230px;flex-shrink:0}.package-execution .px-case-list button.selected{box-shadow:inset 0 -3px var(--runway-accent)}.px-current-case{padding:22px}.px-case-heading h4{font-size:18px}.px-baseline{padding:22px}}
@container execution (max-width:480px){.px-toolbar{padding:17px;align-items:flex-start;flex-direction:column}.px-current-case{padding:17px}.px-case-heading{flex-wrap:wrap}.px-step{padding:14px}.px-observation-state{align-items:flex-start;flex-wrap:wrap;margin-top:7px}.px-step-footer{flex-wrap:wrap;gap:5px}.px-step-footer>.px-link{margin-left:0}.px-case-footer{flex-wrap:wrap}.px-step-progress{flex-wrap:wrap;gap:7px}.px-baseline{padding:17px}}
@media(prefers-reduced-motion:reduce){.package-execution button,.px-step-progress>div>span{transition:none}}
</style>
