import {packageJourney} from './test-packages.mjs';
const issueKey=value=>String(value||'').trim().replace(/\/$/,'').toLowerCase();
export function myWorkRows(snapshot,packages=[]){
 const linked=new Map();for(const pkg of packages){const key=issueKey(pkg.issueUrl);if(!linked.has(key))linked.set(key,[]);linked.get(key).push(pkg)}
 return (snapshot?.issues||[]).map(issue=>{const matches=linked.get(issueKey(issue.html_url))||[];const pkg=[...matches].sort((a,b)=>String(b.updatedAt).localeCompare(String(a.updatedAt)))[0];const journey=pkg?packageJourney(pkg):null;const qaNone=(issue.labels||[]).some(label=>String(label.name||'').trim().toLowerCase()==='qa/none');const planned=!!pkg?.cases?.length;const validation=journey?.stages?.find(stage=>stage.id==='validation');const reproduced=journey?.stages?.find(stage=>stage.id==='reproduction')?.state==='done';const validated=validation?.state==='done';
 return {issue,pkg,matches,qaNone,planned,reproduced,validated,closed:issue.state==='closed',stage:qaNone?'QA not required':!planned?'Needs a plan':validated?'Validated':validation?.state==='active'?'Validating':reproduced?'Ready for validation':'Needs reproduction'};});
}
export function myWorkMetrics(rows){const open=rows.filter(row=>!row.closed&&!row.qaNone);return {total:rows.length,open:open.length,closed:rows.filter(row=>row.closed).length,needsPlan:open.filter(row=>!row.planned).length,planned:open.filter(row=>row.planned).length,needsReproduction:open.filter(row=>row.planned&&!row.reproduced&&!row.validated).length,needsValidation:open.filter(row=>row.reproduced&&!row.validated).length,validated:open.filter(row=>row.validated).length};}
export function filterMyWork(rows,filter='',query=''){const needle=query.trim().toLowerCase();return rows.filter(row=>(!needle||`${row.issue.number} ${row.issue.title}`.toLowerCase().includes(needle.replace(/^#/,'')))&&(filter==='qaNone'?row.qaNone:filter==='open'?!row.closed&&!row.qaNone:filter==='closed'?row.closed:filter==='needsPlan'?!row.closed&&!row.qaNone&&!row.planned:filter==='needsReproduction'?!row.closed&&!row.qaNone&&row.planned&&!row.reproduced&&!row.validated:filter==='needsValidation'?!row.closed&&!row.qaNone&&row.reproduced&&!row.validated:filter==='validated'?!row.closed&&!row.qaNone&&row.validated:true));}
export function workTrend(history=[]){const max=Math.max(1,...history.map(point=>point.open));return history.map((point,i)=>`${history.length===1?0:i/(history.length-1)*300},${80-point.open/max*70}`).join(' ');}
