<script setup>
import {ref} from 'vue';
import {normalizeTeamMembers} from './team-members.mjs';
import {savedTeam,savedTeamMe,saveTeam} from './team-settings-store.mjs';
const props=defineProps({modelValue:{type:Array,default:()=>[]},me:{type:String,default:''},disabled:Boolean});
const emit=defineEmits(['update:modelValue','update:me']);
const username=ref(''),error=ref(''),notice=ref('');
function add(){const name=username.value.trim().replace(/^@/,'').toLowerCase();if(!/^[a-z\d](?:[a-z\d-]{0,37}[a-z\d])?$/i.test(name)||name.includes('--')){error.value='Enter one valid GitHub username.';return;}if(props.modelValue.length>=8){error.value='Choose up to eight team members.';return;}emit('update:modelValue',normalizeTeamMembers([...props.modelValue,name]));username.value='';error.value='';notice.value='';}
function save(){try{saveTeam(props.modelValue,props.me);notice.value='Team saved on this device for My Work and Issue Radar.';}catch{error.value='Unable to save team settings on this device.';}}
function load(){emit('update:modelValue',[...savedTeam.value]);emit('update:me',savedTeamMe.value);}
</script>
<template><fieldset class="team-editor" :disabled="disabled"><legend>Team members</legend><div class="team-cards"><div v-for="user in modelValue" :key="user" class="team-member"><strong>@{{user}}</strong><button type="button" :aria-label="`Remove ${user}`" @click="emit('update:modelValue',modelValue.filter(u=>u!==user))">×</button></div></div><div class="team-add"><input v-model="username" placeholder="GitHub username" aria-label="Add team member" autocapitalize="none" spellcheck="false" @keydown.enter.prevent="add"/><button type="button" :disabled="!username.trim()||modelValue.length>=8" @click="add">+ Add person</button></div><label>Your GitHub username<input :value="me" placeholder="Your username (optional)" autocapitalize="none" @input="emit('update:me',$event.target.value.trim().replace(/^@/,'').toLowerCase())"/></label><div class="team-actions"><button type="button" @click="save">Save as my default team</button><button v-if="savedTeam.length" type="button" @click="load">Use saved team</button></div><small>Used to group assignments. Issues outside your team remain visible.</small><p v-if="error" role="alert">{{error}}</p><p v-if="notice" role="status">{{notice}}</p></fieldset></template>
<style scoped>.team-editor{border:1px solid var(--runway-border);border-radius:10px;padding:14px;display:grid;gap:12px;min-width:0}.team-editor legend{font-size:13px;font-weight:650}.team-cards,.team-add,.team-actions{display:flex;gap:8px;flex-wrap:wrap}.team-member{display:flex;align-items:center;gap:12px;background:var(--runway-card);border:1px solid var(--runway-border);border-radius:8px;padding:10px 12px}.team-member strong{font-size:13px}.team-editor button,.team-editor input{font:inherit;border:1px solid var(--runway-border);border-radius:6px;padding:7px 10px;color:var(--runway-ink);background:var(--runway-card)}.team-editor label{display:grid;gap:6px;max-width:320px;font-size:12px}.team-editor small,.team-editor p{color:var(--runway-muted);font-size:12px}.team-editor button{cursor:pointer}.team-editor :focus-visible{outline:2px solid var(--runway-accent);outline-offset:2px}</style>
