<script setup>
import {ref} from 'vue';
import {apiFetch} from './store.js';
import Icon from './HelmLabIcon.vue';
const props=defineProps({modelValue:Object,disabled:Boolean});
const emit=defineEmits(['update:modelValue']);
const plans=ref([]),loading=ref(false),error=ref(''),opened=ref(false),chosen=ref('');
async function load(){opened.value=true;loading.value=true;error.value='';try{const response=await apiFetch('/api/test-lab');if(!response.ok)throw new Error(await response.text());const data=await response.json();plans.value=(data.library?.plans||[]).filter(p=>p.sha&&p.selection?.length);}catch(e){error.value=e.message;}finally{loading.value=false;}}
function link(){const plan=plans.value.find(p=>p.id===chosen.value);if(!plan||props.disabled)return;emit('update:modelValue',{...props.modelValue,automation:'automated',selection:[...plan.selection],automationSource:{name:plan.name,sha:plan.sha,ref:plan.ref,tags:plan.tags,timeout:plan.timeout}});opened.value=false;}
function unlink(){if(props.disabled)return;const next={...props.modelValue,selection:[]};delete next.automationSource;emit('update:modelValue',next);}
</script>
<template><section class="pa-link" aria-label="Linked Test Lab automation"><template v-if="modelValue.automationSource"><strong><Icon name="flask"/>{{modelValue.automationSource.name}}</strong><small>rancher/tests@{{modelValue.automationSource.sha.slice(0,12)}} · {{modelValue.selection.length}} selections</small><p>The selection, source, tags, and timeout are frozen into each new session. Configure credentials and review commands in Test Lab before executing.</p><button type="button" :disabled="disabled||loading" @click="load">Change linked plan</button><button type="button" :disabled="disabled" @click="unlink">Unlink automation</button></template><template v-else><strong>Make this case repeatable</strong><p>Link a saved Test Lab plan to preserve its exact tests and source revision with this case.</p><button type="button" :disabled="disabled||loading" @click="load"><Icon name="flask"/>Choose Test Lab plan</button></template><p v-if="error" role="alert">{{error}}</p><form v-if="opened" @submit.prevent="link"><label>Saved Test Lab plan<select v-model="chosen" :disabled="disabled||loading" required><option value="">{{loading?'Loading saved plans…':'Choose a plan…'}}</option><option v-for="plan in plans" :key="plan.id" :value="plan.id">{{plan.name}} · {{plan.sha.slice(0,9)}} · {{plan.selection.length}} selections</option></select></label><p v-if="!loading&&!plans.length">Save a plan in Test Lab first, then return here to link it.</p><button type="submit" :disabled="disabled||!chosen||loading">Link this plan</button><button type="button" @click="opened=false">Cancel</button></form></section></template>
<style scoped>.pa-link{padding:15px;border:1px solid var(--runway-border);border-radius:10px;background:var(--runway-card)}strong{display:flex;align-items:center;gap:7px;font-size:12px}svg{width:14px;height:14px}small{display:block;margin-top:7px;color:var(--runway-accent);font:10px ui-monospace,monospace;overflow-wrap:anywhere}p{font-size:11px;color:var(--runway-muted);line-height:1.7}button{display:inline-flex;align-items:center;gap:6px;cursor:pointer;border:1px solid var(--runway-border);border-radius:7px;background:var(--runway-soft);padding:8px 10px;color:var(--runway-accent);font:11px inherit;margin:4px 7px 0 0}button:disabled{opacity:.4;cursor:not-allowed}form{margin-top:15px;border-top:1px solid var(--runway-border);padding-top:12px}label{font-size:11px}select{display:block;width:100%;box-sizing:border-box;margin-top:7px;padding:10px;color:var(--runway-ink);background:var(--runway-input);border:1px solid var(--runway-control);border-radius:7px}:focus-visible{outline:2px solid var(--runway-accent);outline-offset:3px}</style>
