<script setup>
import { computed, ref, reactive, onMounted, onBeforeUnmount, watch, nextTick } from 'vue';
import { stringify } from 'yaml';
import { inspectConfig, setRancherField } from './test-lab-workspace.mjs';
import ConfigEditor from './TestLabEditor.vue';
import RancherTargetPicker from './RancherTargetPicker.vue';
import RancherTokenGenerator from './RancherTokenGenerator.vue';
import {rancherTestHost} from './rancher-connection.mjs';
import ConfigLibrary from './TestLabConfigs.vue';
import Reference from './TestLabReference.vue';
import {testExplorer,filterTestExplorer} from './test-lab-folders.mjs';
import {resolveReadme} from './test-lab-docs.mjs';
import Preflight from './TestLabPreflight.vue';
import Icon from './HelmLabIcon.vue';
import Confirm from './LocalLabConfirm.vue';
import { apiFetch } from './store.js';
import { emptyTestDraft, filterTests, testGroups, toggleTestSelection, selectTestSuites, testDuration, testRunSummary, testRepoURL } from './test-lab.mjs';
import { writeTextToClipboard } from './clipboard.js';
const props=defineProps({active:{type:Boolean,default:true}});
const library=ref({catalog:{entries:[]},plans:[],runs:[],github:{}}), loaded=ref(false),catalogBusy=ref(false),catalogError=ref(''),keychain=ref(false);
const error=ref(''),notice=ref(''),pending=ref(''),view=ref('build'),step=ref(1),query=ref(''),category=ref(''),expanded=ref(new Set()),draft=reactive(emptyTestDraft());
const connectionBusy=ref(false),authMode=ref('password');
const folderQuery=ref(''),folderExpanded=ref(new Set()),explorerKind=ref('all'),selectedFile=ref(''),explorerSearch=ref(null),referenceOpen=ref(false),referenceRequest=ref(0);
const config=ref('rancher:\n  host: ""\n  adminToken: ""\n  clusterName: local\n  cleanup: true\n  insecure: false\n'),advanced=ref(false),showToken=ref(false),remember=ref(false),review=ref(null),confirmation=ref(''),selectedRun=ref(''),log=ref(''),issuesOnly=ref(false),wrap=ref(true),paused=ref(false),dialog=ref(null),sourceRef=ref(null);
const clientID=ref(''),appSlug=ref(''),device=ref(null),repositories=ref([]),repository=ref(''),repoName=ref('rancher-runway-tests'),deleteGuide=ref(false);
let timer,deviceTimer,disposed=false,refreshing=false,loadPlanIntent=null,referenceTrigger;
const controllers=new Set();
const catalog=computed(()=>library.value.catalog||{entries:[]}),github=computed(()=>library.value.github||{}),entries=computed(()=>catalog.value.entries||[]);
const explorer=computed(()=>testExplorer(entries.value,documents.value));
const visibleFiles=computed(()=>filterTestExplorer(explorer.value,folderQuery.value,folderExpanded.value,explorerKind.value));
function toggleFolder(path){const next=new Set(folderExpanded.value);next.has(path)?next.delete(path):next.add(path);folderExpanded.value=next;}
function revealFile(path){const next=new Set(folderExpanded.value),parts=path.split('/');for(let i=2;i<parts.length;i++)next.add(parts.slice(0,i).join('/'));folderExpanded.value=next;}
function selectFolder(path){category.value=path.replace(/^validation\//,'');selectedFile.value='';folderExpanded.value=new Set([...folderExpanded.value,path]);}
function clearFileFilter(){category.value='';selectedFile.value='';}
function selectFile(row){if(row.kind==='readme'){showDocs(row.path);return;}selectedFile.value=row.path;category.value='';query.value='';revealFile(row.path);expanded.value=new Set([...expanded.value,...row.suiteIDs]);}
function browseReadmes(){explorerKind.value='readmes';folderQuery.value='';nextTick(()=>explorerSearch.value?.focus({preventScroll:true}));}
const filtered=computed(()=>filterTests(entries.value,query.value,category.value,selectedFile.value));
const allGroups=computed(()=>new Map(testGroups(entries.value).map(group=>[group.id,group])));
const groups=computed(()=>testGroups(filtered.value).map(group=>({...group,entry:group.entry||allGroups.value.get(group.id)?.entry,totalTests:allGroups.value.get(group.id)?.tests.length||0})));
const selectionCount=computed(()=>draft.selection.length);
const activeRun=computed(()=>library.value.runs.find(r=>r.status==='running'));
const run=computed(()=>library.value.runs.find(r=>r.id===selectedRun.value)),summary=computed(()=>testRunSummary(run.value?.results));
const shownResults=computed(()=>(run.value?.results||[]).filter(r=>!issuesOnly.value||r.status==='fail'));
const configObject=computed(()=>{const result=inspectConfig(config.value);return result.valid?result.value:null;});
const documents=ref([]),docsSHA=ref(''),docsBusy=ref(false),docsError=ref(''),docPath=ref('');
const preflight=ref(null),scanBusy=ref(false),scanError=ref(''),scanSnapshot=ref(''),previousConfig=ref(null),templateName=ref('');
const selectedPackages=computed(()=>[...new Set(entries.value.filter(e=>draft.selection.includes(e.id)).map(e=>e.package))]);
const activeDocPath=computed(()=>referenceOpen.value?resolveReadme(documents.value,docPath.value,selectedPackages.value).doc?.path:'');
const scanKey=()=>JSON.stringify({sha:draft.sha,selection:draft.selection,config:config.value});
const scanStale=computed(()=>!!preflight.value&&scanSnapshot.value!==scanKey());
async function loadDocs(){if(!catalog.value.sha||docsBusy.value)return;const sha=catalog.value.sha;docsBusy.value=true;docsError.value='';try{const data=await request('source-docs',{sha});if(sha===catalog.value.sha){documents.value=data.documents;docsSHA.value=sha;}}catch(e){if(sha===catalog.value.sha)docsError.value=e.message;}finally{docsBusy.value=false;if(sha!==catalog.value.sha&&props.active)loadDocs();}}
function closeReference(){referenceOpen.value=false;nextTick(()=>{if(referenceTrigger?.isConnected)referenceTrigger.focus({preventScroll:true});});}
function showDocs(path=''){if(connectionBusy.value)return;referenceTrigger=document.activeElement;referenceRequest.value++;docPath.value=typeof path==='string'?path:'';referenceOpen.value=true;if(docsSHA.value!==catalog.value.sha)loadDocs();}
function navigateDoc(path){docPath.value=path;revealFile(path);}
async function scan(){if(scanBusy.value)return;const snapshot=scanKey();scanBusy.value=true;scanError.value='';try{const data=await request('preflight',JSON.parse(snapshot));if(snapshot===scanKey()){preflight.value=data;scanSnapshot.value=snapshot;}}catch(e){scanError.value=e.message;}finally{scanBusy.value=false;}}
function useConfig(value){if(connectionBusy.value)return;previousConfig.value=config.value;config.value=value.config;templateName.value=value.name;view.value='build';step.value=2;advanced.value=true;notice.value=`Working copy of “${value.name}” loaded. The saved template stays unchanged.`;}

const rancher=computed(()=>configObject.value?.rancher||{});
const tokenURL=computed(()=>rancherTestHost(rancher.value.host)?`https://${rancherTestHost(rancher.value.host)}`:'');
const tokenConfigValid=computed(()=>{try{setRancherField(config.value,'adminToken',rancher.value.adminToken||'');return true;}catch{return false;}});
const stale=computed(()=>!!draft.sha&&draft.sha!==catalog.value.sha);
const readyToReview=computed(()=>selectionCount.value>0&&!stale.value&&rancher.value.host&&rancher.value.adminToken&&configObject.value&&!pending.value&&!connectionBusy.value);
const date=value=>value?new Date(value).toLocaleString():'';
const short=value=>value?.slice(0,9)||'Not loaded';
const human=value=>String(value||'').replace(/^Test/,'').replace(/([A-Z]+)([A-Z][a-z])/g,'$1 $2').replace(/([a-z0-9])([A-Z])/g,'$1 $2');
async function request(action='',data={}){const controller=new AbortController();controllers.add(controller);const timeout=setTimeout(()=>controller.abort(),95000);try{const response=await apiFetch('/api/test-lab',action?{method:'POST',body:JSON.stringify({action,...data}),signal:controller.signal}:{signal:controller.signal});if(!response.ok)throw new Error(await response.text());return await response.json();}catch(e){if(e.name==='AbortError')throw new Error('The request timed out. Refresh status before retrying an action.');throw e;}finally{clearTimeout(timeout);controllers.delete(controller);}}
async function refresh(){clearTimeout(timer);if(refreshing||disposed)return;refreshing=true;try{const state=await request();if(disposed)return;library.value=state.library;catalogBusy.value=state.catalogBusy;catalogError.value=state.catalogError;keychain.value=state.keychain;loaded.value=true;
 if(!draft.sha&&catalog.value.sha&&!catalogBusy.value){draft.sha=catalog.value.sha;draft.ref=catalog.value.ref;}
 if(loadPlanIntent&&catalog.value.sha===loadPlanIntent.sha){Object.assign(draft,loadPlanIntent);loadPlanIntent=null;}
 if(!selectedRun.value&&activeRun.value)selectedRun.value=activeRun.value.id;
 if(view.value==='activity'&&selectedRun.value&&!paused.value){const value=await request('logs',{id:selectedRun.value});if(!disposed)log.value=value.text;}
 }catch(e){if(!disposed)error.value=e.message;}finally{refreshing=false;if(!disposed&&props.active)timer=setTimeout(refresh,catalogBusy.value||activeRun.value?2500:12000);}}
async function action(name,data={},message=''){if(pending.value)return null;pending.value=name;error.value='';try{const result=await request(name,data);if(message)notice.value=message;await refresh();return result;}catch(e){error.value=e.message;return null;}finally{pending.value='';}}
async function refreshCatalog(){const result=await action('catalog',{ref:draft.ref});if(result){draft.selection=[];draft.sha='';review.value=null;notice.value='Reading public test source. Nothing executes during discovery.';}}
function toggle(entry,event){draft.selection=toggleTestSelection(draft.selection,entry,event.target.checked);draft.sha=catalog.value.sha;review.value=null;}
function expand(id){const next=new Set(expanded.value);next.has(id)?next.delete(id):next.add(id);expanded.value=next;}
function selectVisible(){draft.selection=selectTestSuites(draft.selection,groups.value);draft.sha=catalog.value.sha;review.value=null;}
function updateRancherHost(value){if(rancherTestHost(value)!==rancherTestHost(rancher.value.host))updateRancher('adminToken','');updateRancher('host',value.trim());}
function normalizeRancherHost(){const host=rancherTestHost(rancher.value.host);if(host&&host!==rancher.value.host)updateRancher('host',host);}
function updateRancher(key,value){try{config.value=setRancherField(config.value,key,value);review.value=null;}catch(e){error.value=e.message;}}
async function chooseStep(value){if(connectionBusy.value)return;step.value=value;review.value=null;confirmation.value='';if(value===3){await scan();const snapshot=JSON.stringify({...draft,config:config.value});const result=await action('review',JSON.parse(snapshot));if(result&&step.value===3&&snapshot===JSON.stringify({...draft,config:config.value}))review.value=result;}await nextTick();sourceRef.value?.focus({preventScroll:true});}
function useTarget({target}){
 if(connectionBusy.value)return;const host=rancherTestHost(target.url);if(!host)return;
 try{let text=config.value;if(host!==rancher.value.host){text=setRancherField(text,'adminToken','');text=setRancherField(text,'insecure',false);}text=setRancherField(text,'host',host);config.value=setRancherField(text,'clusterName','local');review.value=null;notice.value='Rancher selected. Sign in with your password, or choose the API token tab.';nextTick(()=>sourceRef.value?.querySelector('input[type=password]')?.focus({preventScroll:true}));}catch(e){error.value=e.message;}
}
async function savePlan(){await action('save-plan',{...draft,config:config.value,remember:remember.value},'Plan saved. Credentials are stored only when Remember is selected.');}
async function loadPlan(id){if(connectionBusy.value)return;const value=await action('load-plan',{id});if(!value)return;Object.assign(draft,value.plan);if(value.config)config.value=value.config;else{config.value=stringify({rancher:{host:value.plan.host,adminToken:'',clusterName:'local',cleanup:true,insecure:false}});}view.value='build';step.value=2;review.value=null;confirmation.value='';if(value.plan.sha!==catalog.value.sha){loadPlanIntent={...value.plan};await action('catalog',{ref:value.plan.sha});notice.value='Loading this plan’s pinned source revision.';}}
async function startRun(){const value=await action('run',{...draft,config:config.value,confirm:confirmation.value});if(value){selectedRun.value=value.id;view.value='activity';confirmation.value='';review.value=null;log.value='';await refresh();}}
async function chooseRun(id){if(connectionBusy.value)return;selectedRun.value=id;view.value='activity';log.value='';paused.value=false;const value=await action('logs',{id});if(value)log.value=value.text;}
async function confirmDialog(){const d=dialog.value;const value=await action(d.action,{id:d.id,name:d.name,repository:d.repository,confirm:d.phrase});if(value){dialog.value=null;if(d.action==='delete-run'&&selectedRun.value===d.id){selectedRun.value='';log.value='';}if(d.action==='github-create'||d.action==='github-link')repository.value=value.full_name;}}
function confirmRemove(action,id){dialog.value={action,id,title:action==='delete-plan'?'Delete saved plan?':'Delete local result?',message:action==='delete-plan'?'Remove this plan and its saved Keychain configuration. Existing test results and Rancher resources stay in place.':'Remove this result and its local activity log. This does not clean up resources in Rancher.',phrase:action==='delete-plan'?'DELETE PLAN':'DELETE RUN',buttonLabel:'Delete locally'};}
async function copyReport(){if(!run.value)return;const r=run.value;await writeTextToClipboard(`# ${r.name}\n\nTarget: ${r.host}\nSource: rancher/tests@${r.sha}\nStatus: ${r.status}\nTags: ${r.tags}\n\n${r.results.map(t=>`${t.status.toUpperCase()} ${t.package} ${t.name} (${testDuration(t.elapsed)})`).join('\n')}\n\n${r.error||''}`);notice.value='Result summary copied.';}
async function signIn(){const value=await action('github-start');if(value){device.value=value;scheduleDevice(value.interval);}}
function scheduleDevice(seconds){clearTimeout(deviceTimer);deviceTimer=setTimeout(pollDevice,Math.max(seconds||5,5)*1000);}
async function pollDevice(){if(disposed||!device.value)return;try{const value=await request('github-poll');if(value.pending)scheduleDevice(value.interval);else{device.value=null;notice.value='GitHub connected. Choose a private repository and grant App access.';await refresh();}}catch(e){error.value=e.message;device.value=null;}}
async function loadRepositories(){const value=await action('github-repositories');if(value)repositories.value=value.repositories;}
function createRepository(){dialog.value={action:'github-create',name:repoName.value,title:'Create a private test repository',message:'GitHub will create a dedicated private repository in your personal account. This can incur Actions usage when tests are run. You may need to grant the Runway App access after creation.',phrase:`${github.value.login}/${repoName.value}`,buttonLabel:'Create private repository'};}
function linkRepository(){dialog.value={action:'github-link',repository:repository.value,title:'Connect this private repository?',message:'Runway will remember this repository as your test workspace. Connecting does not install workflows or run tests.',phrase:repository.value,buttonLabel:'Connect repository'};}
function disconnect(){dialog.value={action:'github-disconnect',title:'Disconnect GitHub?',message:'Forget the saved local connection and its Keychain token. Your repository, workflows, and GitHub App authorization stay on GitHub. You can revoke the authorization in GitHub settings.',phrase:'DISCONNECT',buttonLabel:'Disconnect'};}
watch([config,()=>draft.selection,()=>draft.tags,()=>draft.timeout],()=>{review.value=null;confirmation.value='';});

watch(()=>catalog.value.sha,()=>{documents.value=[];docsSHA.value='';docsError.value='';selectedFile.value='';loadDocs();});
watch(activeDocPath,path=>{if(path)revealFile(path);});
watch(()=>props.active,value=>{if(value)refresh();else clearTimeout(timer);});
onMounted(async()=>{await refresh();if(github.value.login)await action('github-status');});onBeforeUnmount(()=>{disposed=true;clearTimeout(timer);clearTimeout(deviceTimer);controllers.forEach(c=>c.abort());});
</script>

<template>
<div class="test-lab">
 <header class="test-hero">
  <div class="test-hero-top"><span class="test-eyebrow"><Icon name="flask"/> RANCHER RUNWAY / VALIDATION WORKSPACE</span><span class="test-badge"><span :class="{'test-dot-active':activeRun}" class="test-dot"/>{{ activeRun?'Local test running':'Your next finding starts here' }}</span></div>
  <div class="test-hero-title"><div><h2>Test Lab<span>.</span></h2><p>Choose the question. Shape the test. Follow the evidence.</p></div><div class="test-hero-mark" aria-hidden="true"><Icon name="flask"/><span>TEST → LEARN</span></div></div>
  <div class="test-hero-footer"><span><strong>{{ entries.filter(e=>e.test).length.toLocaleString() }}</strong> discovered methods</span><span><strong>{{ testGroups(entries).length }}</strong> suites & entry points</span><span>rancher/tests <code>{{ short(catalog.sha) }}</code></span><button v-if="activeRun" class="test-link" @click="chooseRun(activeRun.id)">Follow active run <Icon name="arrow"/></button></div>
 </header>
 <div v-if="error" role="alert" class="test-message test-error"><Icon name="signal"/><span>{{ error }}</span><button aria-label="Dismiss error" @click="error=''">×</button></div>
 <div v-if="notice" role="status" class="test-message"><Icon name="check"/><span>{{ notice }}</span><button aria-label="Dismiss notice" @click="notice=''">×</button></div>
 <nav class="test-views" aria-label="Test Lab views"><button v-for="item in [{id:'build',label:'Build a run',icon:'sliders'},{id:'activity',label:'Activity & results',icon:'pulse'},{id:'configs',label:'Cattle-config library',icon:'folder'},{id:'saved',label:'Saved plans',icon:'bookmark'},{id:'github',label:'GitHub connection',icon:'branch'}]" :key="item.id" :disabled="connectionBusy" :class="{selected:view===item.id}" :aria-current="view===item.id?'page':undefined" @click="view=item.id;if(item.id==='activity')refresh()"><Icon :name="item.icon"/>{{ item.label }}<span v-if="item.id==='saved'&&library.plans.length" class="test-count">{{ library.plans.length }}</span></button></nav>
 <div v-if="!loaded" class="test-empty" role="status">Opening your test workspace…</div>
 <template v-else-if="view==='build'">
  <div class="test-steps" aria-label="Run preparation"><button v-for="s in [{n:1,title:'Choose tests',detail:'A suite or a single question'},{n:2,title:'Set the target',detail:'Rancher & cattle-config.yml'},{n:3,title:'Review & run',detail:'Know exactly what will execute'}]" :key="s.n" :class="{selected:step===s.n}" :disabled="connectionBusy||(s.n===3&&!readyToReview)" @click="chooseStep(s.n)"><span>{{ String(s.n).padStart(2,'0') }}</span><div><strong>{{ s.title }}</strong><small>{{ s.detail }}</small></div><Icon name="arrow"/></button></div>
  <div ref="sourceRef" tabindex="-1" class="test-stage">
   <template v-if="step===1">
    <div class="test-section-heading"><div><span class="test-eyebrow">THE TEST CATALOG</span><h3>Find the test that fits.</h3><p>Search live validation source. Discovering tests never runs them.</p></div><button class="test-button" :disabled="!catalog.sha" @click="browseReadmes"><Icon name="file"/>Find a README</button><div class="test-ref"><label for="test-source-ref">Branch, tag, or commit</label><div><input id="test-source-ref" v-model="draft.ref" placeholder="main" @keydown.enter="refreshCatalog"/><button class="test-button" :disabled="!!pending||catalogBusy" @click="refreshCatalog"><Icon name="refresh"/>{{ catalogBusy?'Reading source…':entries.length?'Refresh catalog':'Load catalog' }}</button></div></div></div>
    <div v-if="catalogError" class="test-message test-error" role="alert">{{ catalogError }} Your previous catalog is still available.</div>
    <div v-if="stale" class="test-message test-warning">The catalog revision changed. Select tests from this revision before running.</div>
    <div class="test-browser" :class="{'has-reference':referenceOpen}">
     <aside class="test-categories test-folder-browser" aria-label="Validation file explorer">
      <div class="test-folder-heading">
       <div class="test-explorer-title"><span class="test-eyebrow">VALIDATION EXPLORER</span><button type="button" class="test-icon-button" aria-label="Collapse all folders" title="Collapse all folders" @click="folderExpanded=new Set()"><Icon name="folder"/></button></div>
       <div class="test-search"><Icon name="search"/><input ref="explorerSearch" v-model="folderQuery" type="search" aria-label="Find folders or files" placeholder="Find folders or files…"/><button v-if="folderQuery" type="button" class="test-folder-clear" aria-label="Clear file search" @click="folderQuery=''">×</button></div>
       <div class="test-explorer-filters" role="group" aria-label="Show file types"><button v-for="kind in [{id:'all',label:'All files'},{id:'tests',label:'Tests'},{id:'readmes',label:'READMEs'}]" :key="kind.id" type="button" :aria-pressed="explorerKind===kind.id" @click="explorerKind=kind.id">{{ kind.label }}</button></div>
       <button type="button" class="test-all-folders" :class="{selected:!category&&!selectedFile}" @click="clearFileFilter">All runnable tests <span>{{ allGroups.size }} suites</span></button>
       <p v-if="docsBusy" class="test-caption" role="status">Loading README files…</p><p v-else-if="docsError" class="test-explorer-error" role="alert">READMEs couldn't load. <button type="button" class="test-link" @click="loadDocs">Retry</button></p>
      </div>
      <nav class="test-folder-tree" aria-label="Validation folders and files">
       <div v-for="row in visibleFiles" :key="row.key" class="test-folder-row" :class="{'is-selected':row.kind==='folder'?!selectedFile&&category===row.path.replace(/^validation\//,''):row.kind==='test-file'?selectedFile===row.path:activeDocPath===row.path,'is-readme':row.kind==='readme','is-file':row.kind!=='folder'}" :style="{'--folder-depth':row.depth}">
        <template v-if="row.kind==='folder'"><button type="button" class="test-folder-toggle" :aria-label="(folderExpanded.has(row.path)||!!folderQuery?'Collapse ':'Expand ')+row.path.replace(/^validation\//,'')" :aria-expanded="folderExpanded.has(row.path)||!!folderQuery" :disabled="!!folderQuery" @click="toggleFolder(row.path)"><Icon name="chevron"/></button><button type="button" class="test-folder-select" :title="row.path" :aria-current="!selectedFile&&category===row.path.replace(/^validation\//,'')?'true':undefined" @click="selectFolder(row.path)"><Icon name="folder"/><span><strong>{{ row.name }}</strong></span><small v-if="row.count" :title="row.count+' runnable suites'">{{ row.count }}</small></button></template>
        <button v-else type="button" class="test-folder-select test-explorer-file" :title="row.path" :aria-label="(row.kind==='readme'?'Read README ':'Show tests in ')+row.path.replace(/^validation\//,'')" :aria-current="(row.kind==='readme'?activeDocPath===row.path:selectedFile===row.path)?'true':undefined" @click="selectFile(row)"><Icon :name="row.kind==='readme'?'file':'flask'"/><span><strong>{{ row.name }}</strong></span><small>{{ row.kind==='readme'?'MD':row.count }}</small></button>
       </div>
       <p v-if="!visibleFiles.length" class="test-folder-empty">{{ folderQuery?'No folders or files match “'+folderQuery+'”.':docsBusy?'Loading files…':'No files match this filter.' }}</p>
      </nav>
      <div class="test-explorer-legend"><span><Icon name="flask"/>Test files show runnable cases</span><span><Icon name="file"/>READMEs open alongside</span></div>
     </aside>

     <div class="test-catalog"><div v-if="selectedFile||category" class="test-catalog-location"><Icon :name="selectedFile?'flask':'folder'"/><div><small>{{ selectedFile?'RUNNABLE TESTS IN':'TESTS UNDER' }}</small><code>{{ (selectedFile||category).replace(/^validation\//,'') }}</code></div><button type="button" class="test-icon-button" aria-label="Show all runnable tests" title="Show all runnable tests" @click="clearFileFilter"><Icon name="close"/></button></div><div class="test-search"><Icon name="search"/><input v-model="query" type="search" aria-label="Search tests" placeholder="Search tests, suites, packages, or build tags…"/></div><div class="test-list-meta"><span>{{ groups.length }} matching {{ groups.length===1?'suite':'suites' }} <span v-if="catalog.fetchedAt">· Updated {{ date(catalog.fetchedAt) }}</span></span><button v-if="groups.length&&groups.length<=100" class="test-link" @click="selectVisible">Select visible suites</button></div>
      <div v-if="!entries.length" class="test-empty"><Icon name="flask"/><h4>A whole validation library, within reach.</h4><p>Load the public catalog from rancher/tests to browse suites and individual tests. Choose a branch or tag to match your Rancher version.</p><button class="test-button test-primary" :disabled="catalogBusy||!!pending" @click="refreshCatalog">{{ catalogBusy?'Reading test source…':'Explore validation tests' }}</button></div>
      <div v-else-if="!groups.length" class="test-empty"><h4>No matches yet.</h4><p>Try a suite name, package, or a broader search.</p><button class="test-button" @click="query='';clearFileFilter()">Clear filters</button></div>
      <div v-else class="test-suite-list"><article v-for="group in groups" :key="group.id" class="test-suite" :class="{'is-selected':draft.selection.some(id=>id===group.id||id.startsWith(group.id+'/'))}"><div class="test-suite-top"><input type="checkbox" :aria-label="'Select whole suite '+group.suite" :checked="draft.selection.includes(group.id)" :indeterminate="!draft.selection.includes(group.id)&&draft.selection.some(id=>id.startsWith(group.id+'/'))" @change="toggle(group.entry||{id:group.id,package:group.package,suite:group.suite,test:''},$event)"/><button class="test-suite-name" :aria-expanded="expanded.has(group.id)" @click="expand(group.id)"><small>{{ group.package }}</small><strong>{{ human(group.suite) }}</strong></button><span class="test-count">{{ group.tests.length?`${group.tests.length} ${group.tests.length===1?'test':'tests'}`:'Entry point' }}</span><button class="test-icon-button" :aria-label="(expanded.has(group.id)?'Collapse ':'Expand ')+group.suite" @click="expand(group.id)">{{ expanded.has(group.id)?'−':'+' }}</button></div><div v-if="expanded.has(group.id)" class="test-methods"><p v-if="group.entry?.description">{{ group.entry.description }}</p><div class="test-suite-info"><code>{{ group.suite }}</code><button class="test-link" @click="showDocs(group.package+'/README.md')">README & guides</button></div><label v-for="entry in group.tests" :key="entry.id" class="test-method"><input type="checkbox" :checked="draft.selection.includes(entry.id)||draft.selection.includes(group.id)" :disabled="draft.selection.includes(group.id)" @change="toggle(entry,$event)"/><span><strong>{{ human(entry.test) }}</strong><small>{{ entry.test }}</small></span></label><p v-if="selectedFile&&group.totalTests>group.tests.length" class="test-file-suite-note">Showing {{ group.tests.length }} of {{ group.totalTests }} cases. The whole suite also runs cases outside this view.</p><p class="test-caption">Build condition: <code>{{ group.entry?.constraint||'No explicit build constraint' }}</code></p><p v-if="draft.selection.includes(group.id)" class="test-caption">Whole suite selected. Uncheck the suite to choose individual methods.</p></div></article></div>
     </div>
     <Reference v-if="referenceOpen" :documents="documents" :sha="catalog.sha" :packages="selectedPackages" :initial-path="docPath" :request-nonce="referenceRequest" :docs-busy="docsBusy" :docs-error="docsError" @reload="loadDocs" @close="closeReference" @navigate="navigateDoc"/>
    </div>
    <div class="test-selection-bar"><span><strong>{{ selectionCount }}</strong> {{ selectionCount===1?'selection':'selections' }} <button v-if="selectionCount" class="test-link" @click="draft.selection=[]">Clear</button></span><p>Dynamic subtests appear in results. Suite setup and cleanup still run.</p><button class="test-button test-primary" :disabled="!selectionCount||stale" @click="chooseStep(2)">Set the target <Icon name="arrow"/></button></div>
   </template>
   <template v-else-if="step===2">
    <div class="test-section-heading"><div><span class="test-eyebrow">THE ENVIRONMENT</span><h3>Give your tests a destination.</h3><p>Use a detected Rancher or configure another environment. Your draft stays here as you explore Runway.</p></div></div>
    <div class="test-config-grid" :class="{'test-config-editing':advanced}"><div class="test-form-card"><div class="test-card-heading"><Icon name="globe"/><h4>Rancher connection</h4><button type="button" class="test-link" :disabled="connectionBusy||(advanced&&!configObject)" @click="advanced=!advanced">{{ advanced?'Use guided fields':'Edit YAML' }}</button></div>
     <div class="rancher-methods" role="group" aria-label="Connection method"><button v-for="method in [{id:'password',name:'URL + password',icon:'lock'},{id:'token',name:'URL + API token',icon:'key'}]" :key="method.id" type="button" :aria-pressed="authMode===method.id" :disabled="connectionBusy||!!pending" @click="authMode=method.id;showToken=false"><Icon :name="method.icon"/>{{ method.name }}</button></div>
     <RancherTargetPicker purpose="test" :url="tokenURL" :disabled="!!pending||connectionBusy||!tokenConfigValid" @select="useTarget"/>
     <fieldset class="rancher-test-fields" :disabled="connectionBusy||!tokenConfigValid"><legend class="lab-sr-only">Rancher sign-in</legend><label class="rancher-connection-url">Rancher URL or hostname<input :value="rancher.host" placeholder="https://rancher.example.com" autocomplete="off" spellcheck="false" @input="updateRancherHost($event.target.value)" @blur="normalizeRancherHost"/><small v-if="rancher.host&&!tokenURL" class="test-error-text">Use an HTTPS Rancher URL or hostname, without a path.</small></label><label v-if="authMode==='token'">Rancher API token<div class="test-secret"><input :value="rancher.adminToken" :type="showToken?'text':'password'" autocomplete="off" spellcheck="false" placeholder="token-…:…" @input="updateRancher('adminToken',$event.target.value)"/><button type="button" :aria-label="showToken?'Hide token':'Show token'" @click="showToken=!showToken">{{ showToken?'Hide':'Show' }}</button></div><small>For a local account or SSO, use a user token with the access these tests require.</small></label></fieldset>
     <RancherTokenGenerator v-if="authMode==='password'" purpose="test" :url="tokenURL" :credential-available="!!String(rancher.adminToken||'').trim()" :insecure="rancher.insecure===true" :disabled="!!pending||!tokenConfigValid" @busy="connectionBusy=$event" @generated="updateRancher('adminToken',$event.token)"/>
     <fieldset class="rancher-test-fields" :disabled="connectionBusy"><legend class="lab-sr-only">Test configuration</legend><details v-if="!advanced" class="rancher-connection-details"><summary><Icon name="sliders"/>Test connection settings <small>· cluster, cleanup &amp; TLS</small></summary><label>Cluster name<input :value="rancher.clusterName" placeholder="local" @input="updateRancher('clusterName',$event.target.value)"/><small>The Rancher cluster name expected by the selected suite.</small></label><label class="test-check"><input type="checkbox" :checked="rancher.cleanup!==false" @change="updateRancher('cleanup',$event.target.checked)"/><span>Let tests clean up their resources</span></label><label class="test-check"><input type="checkbox" :checked="rancher.insecure===true" @change="updateRancher('insecure',$event.target.checked)"/><span>Allow a self-signed Rancher certificate</span></label></details>
     <template v-else><ConfigEditor v-model="config"/><p class="test-caption">Comments, provider settings, and suite-specific fields stay intact when updating guided fields.</p></template></fieldset>
    <div class="test-config-launcher test-connection-library" :inert="connectionBusy"><div><Icon name="folder"/><span><strong>{{ templateName?'Working copy · '+templateName:'Start from a config you trust.' }}</strong><small>Reuse a saved environment, then tailor it for this run.</small></span></div><div class="test-inline-actions"><button v-if="previousConfig!==null" class="test-link" @click="config=previousConfig;previousConfig=null;templateName=''">Restore previous draft</button><button class="test-button" @click="view='configs'">Open cattle-config library <Icon name="arrow"/></button><button class="test-link" :disabled="!catalog.sha" @click="showDocs()">Browse READMEs</button></div></div>
    </div><div class="test-config-side"><div class="test-form-card"><span class="test-eyebrow">EXECUTION DETAILS</span><h4>Make this run yours.</h4><label>Run / saved plan name<input v-model="draft.name" placeholder="ConfigMap regression · staging" maxlength="100"/></label><label>Build tags<input v-model="draft.tags" spellcheck="false"/><small>Comma-separated Go tags. Each selected test’s build condition is checked before execution.</small></label><label>Timeout per suite<div class="test-number"><input v-model.number="draft.timeout" type="number" min="1" max="240"/><span>minutes</span></div><small>Compilation gets an additional 10 minutes. Suites run sequentially.</small></label></div><div class="test-note"><Icon name="layers"/><div><strong>Every suite has its own requirements.</strong><p>The guided fields cover a basic Rancher connection. Provisioning and provider suites may need more configuration or credentials. Browse the package README, edit the complete YAML, and run a source-informed preflight below.</p></div></div><div class="test-form-card"><h4>Keep a repeatable plan.</h4><label class="test-check"><input v-model="remember" type="checkbox" :disabled="!keychain"/><span>Remember configuration in macOS Keychain</span></label><p class="test-caption">With this off, only the test selection, target hostname, and run options are saved.</p><button class="test-button" :disabled="!draft.name||!readyToReview" @click="savePlan"><Icon name="folder"/>Save plan</button></div></div></div>

    <Preflight :result="preflight" :busy="scanBusy" :stale="scanStale" :error="scanError" @scan="scan" @docs="showDocs"/>
    <div class="test-selection-bar"><button class="test-button" :disabled="connectionBusy" @click="chooseStep(1)">Back to tests</button><span>{{ selectionCount }} {{ selectionCount===1?'selection':'selections' }} · {{ short(draft.sha) }}</span><button class="test-button test-primary" :disabled="!readyToReview" @click="chooseStep(3)">Review this run <Icon name="arrow"/></button></div>
   </template>
   <template v-else>
    <div class="test-section-heading"><div><span class="test-eyebrow">THE FINAL LOOK</span><h3>Know what happens next.</h3><p>Review the target, pinned source, and exact commands before executing integration tests.</p></div></div>
    <div v-if="pending==='review'" class="test-empty" role="status">Checking configuration and selected build conditions…</div>
    <template v-if="review"><div class="test-review-facts"><div><small>DESTINATION</small><strong>{{ review.host }}</strong></div><div><small>EXECUTION</small><strong>This computer</strong></div><div><small>SOURCE REVISION</small><code>{{ review.sha }}</code></div><div><small>SCOPE</small><strong>{{ review.commands.length }} sequential {{ review.commands.length===1?'suite':'suites' }}</strong></div></div>
     <Preflight :result="preflight" :busy="scanBusy" :stale="scanStale" :error="scanError" @scan="scan" @docs="showDocs"/>
     <div class="test-note"><Icon name="signal"/><div><strong>Run against an environment you can change.</strong><ul><li v-for="warning in review.warnings" :key="warning">{{ warning }}</li></ul></div></div>
     <details class="test-command-details"><summary>Inspect {{ review.commands.length }} exact Go command{{ review.commands.length===1?'':'s' }}</summary><pre v-for="command in review.commands" :key="command.package+command.pattern">go {{ command.args.map(a=>/[^a-zA-Z0-9_./=-]/.test(a)?JSON.stringify(a):a).join(' ') }}</pre><p>Required by source: Go {{ review.goVersion||'version in go.mod' }}. Dependencies and a matching Go toolchain may download on first run.</p></details>
     <div class="test-run-confirm"><div><h4>Ready to learn something?</h4><p>Type <strong>{{ review.confirmation }}</strong> to confirm this target.</p><input v-model="confirmation" :placeholder="review.confirmation" aria-label="Confirm test target" autocomplete="off" spellcheck="false" @keydown.enter="confirmation===review.confirmation&&startRun()"/></div><button class="test-button test-primary" :disabled="!!pending||!!activeRun||!review.goPath||confirmation!==review.confirmation" @click="startRun"><Icon name="play"/>Run locally</button></div><p v-if="!review.goPath" class="test-error-text">Go was not found. Install Go and reopen Runway to run locally.</p><p v-if="activeRun" class="test-caption">Another local test is running. Open Activity to follow or stop it.</p>
    </template><button v-if="!review&&!pending" class="test-button" @click="chooseStep(2)">Return to configuration</button>
   </template>
  </div>
 </template>
 <div v-else-if="view==='activity'" class="test-stage">
  <div class="test-section-heading"><div><span class="test-eyebrow">THE EVIDENCE</span><h3>Every run tells a story.</h3><p>Live activity and saved results, with the exact source revision attached.</p></div><button v-if="activeRun" class="test-button test-danger" :disabled="!!pending" @click="dialog={action:'cancel',title:'Stop the active local run?',message:'The process will be interrupted. Suite cleanup may not finish; inspect the target for remaining resources.',phrase:'STOP TESTS',buttonLabel:'Stop tests'}"><Icon name="stop"/>Stop active run</button></div>
  <div v-if="!library.runs.length" class="test-empty"><Icon name="pulse"/><h4>Your first result is waiting to happen.</h4><p>Choose a test and a Rancher target to start building your evidence trail.</p><button class="test-button test-primary" @click="view='build'">Build a run</button></div>
  <div v-else class="test-activity-grid"><aside class="test-history"><button v-for="r in library.runs" :key="r.id" :class="{selected:r.id===selectedRun}" @click="chooseRun(r.id)"><span :class="'test-status status-'+r.status">{{ r.status }}</span><strong>{{ r.name }}</strong><small>{{ date(r.startedAt) }}</small><small>{{ short(r.sha) }}</small></button></aside><div v-if="run" class="test-run-detail"><div class="test-card-heading"><div><h4>{{ run.name }}</h4><p>{{ run.stage }} · {{ run.host }}</p></div><button class="test-button" @click="copyReport">Copy summary</button></div><div class="test-result-counts"><span><strong>{{ summary.passed }}</strong> passed</span><span><strong>{{ summary.failed }}</strong> failed</span><span><strong>{{ summary.skipped }}</strong> skipped</span><span v-if="summary.running"><strong>{{ summary.running }}</strong> running</span></div><div v-if="run.error" class="test-message test-error">{{ run.error }}</div><div class="test-log-toolbar"><strong>Activity</strong><label class="test-check"><input v-model="wrap" type="checkbox"/>Wrap lines</label><label class="test-check"><input v-model="paused" type="checkbox"/>Pause view</label><button class="test-link" @click="refresh">Refresh</button></div><pre class="test-log" :class="{'test-wrap':wrap}" tabindex="0" aria-label="Test activity log">{{ log||'Waiting for output. The first run may need to download Go modules and compile the suite.' }}</pre><div class="test-log-toolbar"><strong>Test results</strong><label class="test-check"><input v-model="issuesOnly" type="checkbox"/>Failures only</label></div><div class="test-results"><div v-for="result in shownResults" :key="result.package+result.name"><span :class="'test-status status-'+result.status">{{ result.status }}</span><code>{{ result.name }}</code><small>{{ testDuration(result.elapsed) }}</small></div><p v-if="!shownResults.length" class="test-caption">{{ issuesOnly?'No failing test results recorded.':'Results appear as tests execute.' }}</p></div><p class="test-caption">Counts include suite and subtest events. Known configuration values are redacted; review logs before sharing. Canceling a test does not remove resources.</p><button v-if="run.status!=='running'" class="test-link test-danger" @click="confirmRemove('delete-run',run.id)">Delete this local result…</button></div><div v-else class="test-empty">Choose a run to inspect its results.</div></div>
 </div>
 <div v-else-if="view==='saved'" class="test-stage"><div class="test-section-heading"><div><span class="test-eyebrow">READY TO REPEAT</span><h3>Good experiments deserve a second run.</h3><p>Saved test selections, pinned revisions, and optional Keychain configurations.</p></div><button class="test-button" @click="view='build';step=2">Save the current draft</button></div><div v-if="!library.plans.length" class="test-empty"><Icon name="folder"/><h4>A place for your go-to checks.</h4><p>Name a run in Set the target, then save it here for next time.</p></div><div class="test-plan-grid"><article v-for="plan in library.plans" :key="plan.id" class="test-form-card"><span class="test-eyebrow">{{ plan.hasConfig?'CONFIGURATION IN KEYCHAIN':'TEST PLAN' }}</span><h4>{{ plan.name }}</h4><p>{{ plan.host }}</p><div class="test-plan-meta"><span>{{ plan.selection.length }} selections</span><code>{{ short(plan.sha) }}</code></div><small>{{ date(plan.savedAt) }}</small><div class="test-plan-actions"><button class="test-button test-primary" :disabled="!!pending" @click="loadPlan(plan.id)">Use this plan <Icon name="arrow"/></button><button class="test-icon-button" :aria-label="'Delete plan '+plan.name" @click="confirmRemove('delete-plan',plan.id)"><Icon name="trash"/></button></div></article></div></div>
 <div v-else-if="view==='github'" class="test-stage">
  <div class="test-section-heading"><div><span class="test-eyebrow">YOUR TESTS. YOUR WORKSPACE.</span><h3>A home for tests on GitHub.</h3><p>Authorize Runway, then choose a private repository you own. Keep control of the connection.</p></div><span class="test-badge">{{ github.connected?'Connected':github.login?'Reconnect needed':'Not connected' }}</span></div>
  <div class="test-github-grid"><div class="test-form-card"><span class="test-step-number">01</span><h4>Connect your account</h4><p>Sign in through GitHub. Runway stores its user token in macOS Keychain and refreshes it when needed.</p>
   <div v-if="!github.clientId" class="test-note"><div><strong>One-time integration registration needed.</strong><p>The Runway maintainer must register a GitHub App and enable device flow. Users can then authorize that same integration.</p><a href="https://github.com/settings/apps/new" target="_blank" rel="noreferrer">Open GitHub App registration ↗</a></div></div>
   <details v-if="!github.login" class="test-advanced"><summary>Integration configuration</summary><label>Registered App client ID<input v-model="clientID" :placeholder="github.clientId||'Iv1.…'"/></label><label>App slug<input v-model="appSlug" :placeholder="github.slug||'rancher-runway'"/></label><button class="test-button" :disabled="!!pending||!clientID||!appSlug" @click="action('github-config',{clientId:clientID,slug:appSlug},'Integration configured. You can now authorize it.')">Save integration</button><p class="test-caption">Client ID is public. A client secret or private key must never be bundled with the desktop app. See docs/test-lab.md for registration permissions.</p></details>
   <div v-if="device" class="test-device"><p>Enter this code on GitHub:</p><strong>{{ device.userCode }}</strong><a :href="device.url" target="_blank" rel="noreferrer" class="test-button test-primary">Authorize on GitHub ↗</a><small>Waiting for authorization. Expires {{ date(device.expiresAt) }}.</small></div>
   <template v-else><p v-if="github.login" class="test-connected"><Icon name="check"/>{{ github.login }}</p><button class="test-button test-primary" :disabled="!!pending||!github.clientId||!keychain" @click="signIn">{{ github.login?'Reconnect GitHub':'Connect GitHub' }} <Icon name="arrow"/></button><button v-if="github.login" class="test-link" :disabled="!!pending" @click="action('github-status')">Verify connection</button></template>
  </div><div class="test-form-card"><span class="test-step-number">02</span><h4>Choose your test repository</h4><p>A dedicated private repository keeps test workflows and results organized under your account.</p><template v-if="github.login"><p v-if="github.repository"><a :href="testRepoURL(github.repository)" target="_blank" rel="noreferrer"><strong>{{ github.repository }} ↗</strong></a><br/><small>{{ github.repositoryStatus }}</small></p><label>New private repository name<input v-model="repoName" maxlength="100"/></label><button class="test-button" :disabled="!!pending||!github.connected" @click="createRepository">Create private repository…</button><div class="test-divider">or connect an existing private repository</div><label>Owner / repository<input v-model="repository" placeholder="your-account/rancher-runway-tests"/></label><div class="test-inline-actions"><button class="test-button" :disabled="!!pending||!repository" @click="linkRepository">Connect repository…</button><button class="test-link" :disabled="!!pending" @click="loadRepositories">Browse available</button></div><div v-if="repositories.length" class="test-repo-list"><button v-for="repo in repositories" :key="repo.full_name" @click="repository=repo.full_name">{{ repo.full_name }}</button></div><a v-if="github.slug" :href="`https://github.com/apps/${encodeURIComponent(github.slug)}/installations/new`" target="_blank" rel="noreferrer" class="test-install-link">Grant the App access to your repository ↗</a><p class="test-caption">Creating or authorizing an account does not automatically grant the App access to every repository. Organization policy may require an owner’s approval.</p></template><p v-else class="test-caption">Connect your GitHub account to choose a repository.</p></div></div>
  <div class="test-note"><Icon name="globe"/><div><strong>Cloud execution is the next connection step.</strong><p>This first version connects your account and repository. Workflow installation and Actions execution are not enabled yet. Local execution is ready to use. A GitHub runner will need network access to your Rancher; it cannot reach your laptop’s localhost or private VPN by default.</p></div></div>
  <div v-if="github.login" class="test-connection-management"><div><h4>You stay in control.</h4><p>Disconnecting forgets local credentials. Repository deletion always happens manually on GitHub.</p></div><div class="test-inline-actions"><button v-if="github.repository" class="test-button" :disabled="!!pending" @click="action('github-unlink',{},'Repository disconnected. Files on GitHub are unchanged.')">Disconnect repository</button><button class="test-button" @click="disconnect">Disconnect GitHub…</button><button v-if="github.repository&&github.createdRepository" class="test-link test-danger" @click="deleteGuide=!deleteGuide">Delete repository on GitHub…</button></div></div>
  <div v-if="deleteGuide&&github.repository" class="test-delete-guide"><h4>Delete this repository yourself on GitHub</h4><p>Runway cannot delete repositories. On GitHub, open <strong>{{ github.repository }}</strong> → Settings → General → Danger Zone → Delete this repository. Review GitHub’s warnings and confirm there.</p><a class="test-button test-danger" :href="testRepoURL(github.repository,true)" target="_blank" rel="noreferrer">Open repository settings ↗</a><p>Disconnect it here afterward. If access disappears, Runway labels it “Repository unavailable” because permissions may also have changed.</p></div><p v-if="github.login" class="test-caption">To revoke GitHub authorization or uninstall the App, use <a href="https://github.com/settings/apps/authorizations" target="_blank" rel="noreferrer">GitHub settings ↗</a>.</p>
 </div>
 <div v-if="loaded" v-show="view==='configs'" class="test-stage"><ConfigLibrary :request="request" :active="view==='configs'" :current-config="config" @use="useConfig" @close="view='build'"/></div>
 <div v-if="loaded&&referenceOpen&&(view!=='build'||step!==1)" class="test-reference-below"><Reference v-if="referenceOpen" :documents="documents" :sha="catalog.sha" :packages="selectedPackages" :initial-path="docPath" :request-nonce="referenceRequest" :docs-busy="docsBusy" :docs-error="docsError" @reload="loadDocs" @close="closeReference" @navigate="navigateDoc"/></div>
 <Confirm v-if="dialog" :title="dialog.title" :message="dialog.message" :phrase="dialog.phrase" :button-label="dialog.buttonLabel" :busy="!!pending" @cancel="dialog=null" @confirm="confirmDialog"/>
</div>
</template>
