<script setup>
import {computed,ref} from 'vue';
import Icon from './HelmLabIcon.vue';
import {libraryGroups,moveLibraryPackage,reorderLibraryBucket,deleteLibraryBucket} from './test-package-library.mjs';
import {newPackageRecordID,packageStatus} from './test-packages.mjs';
const props=defineProps({library:Object,packages:Array,visible:Array,selectedId:String,busy:Boolean});
const emit=defineEmits(['select','save','export']);
const newName=ref(''),creating=ref(false),collapsed=ref(new Set()),renaming=ref(''),renameText=ref(''),moving=ref(''),dragged=ref('');
const groups=computed(()=>libraryGroups(props.library,props.packages||[]));
const visibleIds=computed(()=>new Set((props.visible||[]).map(p=>p.id)));
function copy(){return JSON.parse(JSON.stringify(props.library));}
function create(){if(props.busy||!newName.value.trim())return;const next=copy();next.buckets.push({id:newPackageRecordID(),name:newName.value.trim(),packageIds:[]});emit('save',next);creating.value=false;newName.value='';}
function rename(id){if(props.busy||!renameText.value.trim())return;const next=copy();next.buckets.find(b=>b.id===id).name=renameText.value.trim();emit('save',next);renaming.value='';}
function remove(id){if(props.busy)return;emit('save',deleteLibraryBucket(props.library,id));}
function move(id,bucket,index){if(props.busy)return;emit('save',moveLibraryPackage(copy(),id,bucket,index));moving.value='';dragged.value='';}
function toggle(id){const next=new Set(collapsed.value);next.has(id)?next.delete(id):next.add(id);collapsed.value=next;}
function drop(event,bucket,index){event.preventDefault();if(dragged.value)move(dragged.value,bucket,index);}
</script>
<template>
 <div class="pl-library">
 <div class="pl-organization"><span>Milestone buckets</span><button type="button" :disabled="busy" @click="creating=!creating" aria-label="Create milestone bucket"><Icon name="plus"/></button></div>
 <form v-if="creating" class="pl-inline" @submit.prevent="create"><label>Milestone name<input v-model="newName" maxlength="120" required placeholder="v2.16.0 · Frameworks" :disabled="busy"/></label><button :disabled="busy||!newName.trim()">Create bucket</button><button type="button" @click="creating=false">Cancel</button></form>
 <section v-for="(group,groupIndex) in groups" :key="group.id" class="pl-bucket" :aria-label="group.name+' packages'" @dragover.prevent @drop="drop($event,group.id)">
  <header><button type="button" class="pl-heading" :aria-expanded="!collapsed.has(group.id)" @click="toggle(group.id)"><Icon name="folder"/><strong>{{group.name}}</strong><span>{{group.packages.length}}</span></button><details class="pl-menu"><summary :aria-label="'Options for '+group.name"><Icon name="sliders"/></summary><div @click="$event.currentTarget.closest('details')?.removeAttribute('open')"><template v-if="group.id!=='unfiled'"><button type="button" :disabled="busy" @click="renaming=group.id;renameText=group.name">Rename bucket</button><button type="button" :disabled="busy||groupIndex===0" @click="emit('save',reorderLibraryBucket(copy(),group.id,-1))">Move bucket up</button><button type="button" :disabled="busy||groupIndex===groups.length-2" @click="emit('save',reorderLibraryBucket(copy(),group.id,1))">Move bucket down</button><button type="button" :disabled="busy" title="Packages move to Unfiled, keeping their order and history." @click="remove(group.id)">Delete bucket</button></template><button type="button" :disabled="busy||!group.packages.length" @click="emit('export',group.id)">Export this bucket…</button></div></details></header>
  <form v-if="renaming===group.id" class="pl-inline" @submit.prevent="rename(group.id)"><label>Bucket name<input v-model="renameText" maxlength="120" required/></label><button :disabled="busy">Save name</button><button type="button" @click="renaming=''">Cancel</button></form>
  <div v-if="!collapsed.has(group.id)" class="pl-items">
   <p v-if="!group.packages.length" class="pl-empty">Move a package here to prepare this milestone.</p>
   <article v-for="(pkg,index) in group.packages" v-show="visibleIds.has(pkg.id)" :key="pkg.id" class="pl-item" :class="{selected:selectedId===pkg.id}" :draggable="!busy" @dragstart="dragged=pkg.id;$event.dataTransfer.effectAllowed='move'" @dragend="dragged=''" @dragover.stop.prevent @drop.stop="drop($event,group.id,index)">
    <button type="button" class="pl-package" :disabled="busy" :aria-current="selectedId===pkg.id?'true':undefined" @click="emit('select',pkg.id)"><strong>{{pkg.title}}</strong><small>{{pkg.issueTitle||pkg.issueUrl?.split('/').slice(-2).join(' #')||'Independent investigation'}}</small><span :data-status="pkg.status">{{packageStatus(pkg.status)}}</span></button>
    <details class="pl-menu"><summary :aria-label="'Organize '+pkg.title"><Icon name="sliders"/></summary><div @click="$event.currentTarget.closest('details')?.removeAttribute('open')"><button type="button" :disabled="busy" @click="moving=pkg.id">Move to bucket…</button><button type="button" :disabled="busy||index===0" @click="move(pkg.id,group.id,index-1)">Move package up</button><button type="button" :disabled="busy||index===group.packages.length-1" @click="move(pkg.id,group.id,index+1)">Move package down</button></div></details>
    <label v-if="moving===pkg.id" class="pl-move">Destination<select aria-label="Destination" :disabled="busy" :value="group.id" @change="move(pkg.id,$event.target.value)"><option v-for="bucket in groups" :key="bucket.id" :value="bucket.id">{{bucket.name}}</option></select><button type="button" @click="moving=''">Cancel</button></label>
   </article>
  </div>
 </section>
 <button type="button" class="pl-export-all" :disabled="busy||!packages.length" @click="emit('export','')"><Icon name="download"/>Export library…</button>
 </div>
</template>
<style scoped>
.pl-library{width:100%;min-width:0;flex:1 0 100%}

.pl-organization{display:flex;align-items:center;justify-content:space-between;padding:12px 16px;font-size:10px;text-transform:uppercase;letter-spacing:.1em;color:var(--runway-muted)}button,summary{cursor:pointer;font:inherit}button:disabled{opacity:.4;cursor:not-allowed}svg{width:14px;height:14px}button{background:none;border:0;color:var(--runway-ink)}:focus-visible{outline:2px solid var(--runway-accent);outline-offset:2px}.pl-organization button{display:grid;place-items:center;padding:5px}.pl-bucket{border-bottom:1px solid var(--runway-border);padding:7px 9px}.pl-bucket>header{display:flex;align-items:center;gap:6px}.pl-heading{display:flex;align-items:center;gap:8px;text-align:left;flex:1;min-width:0;padding:9px 5px}.pl-heading strong{font-size:12px;overflow-wrap:anywhere}.pl-heading span{margin-left:auto;font-size:10px;background:var(--runway-soft);border:1px solid var(--runway-border);border-radius:6px;padding:2px 6px}.pl-heading svg{color:var(--runway-accent);flex-shrink:0}.pl-empty{font-size:11px;line-height:1.6;color:var(--runway-muted);padding:0 7px 10px}.pl-item{display:flex;align-items:flex-start;border:1px solid transparent;border-radius:10px;margin:4px 0;flex-wrap:wrap}.pl-item:hover{background:var(--runway-soft)}.pl-item.selected{background:var(--runway-accent-soft);border-color:var(--runway-border)}.pl-package{flex:1;min-width:0;text-align:left;padding:12px 9px}.pl-package strong{display:block;font-size:12px;line-height:1.5;overflow-wrap:anywhere}.pl-package small{display:block;font-size:10px;line-height:1.5;color:var(--runway-muted);margin:4px 0;overflow-wrap:anywhere}.pl-package>span{font-size:9px;color:var(--runway-accent)}.pl-menu{position:relative;flex-shrink:0}.pl-menu>summary{list-style:none;display:grid;place-items:center;width:25px;height:32px;color:var(--runway-muted)}.pl-menu>summary::-webkit-details-marker{display:none}.pl-menu>div{position:absolute;right:0;top:100%;z-index:20;width:190px;display:grid;padding:5px;background:var(--runway-raised);border:1px solid var(--runway-border);border-radius:9px;box-shadow:var(--runway-shadow)}.pl-menu button{text-align:left;padding:9px;border-radius:5px;font-size:11px}.pl-menu button:hover{background:var(--runway-soft)}.pl-inline,.pl-move{display:flex;gap:7px;flex-wrap:wrap;padding:10px;font-size:11px}.pl-inline label,.pl-move{width:100%}.pl-inline input,.pl-move select{width:100%;box-sizing:border-box;padding:8px;margin-top:5px;border:1px solid var(--runway-control);border-radius:7px;background:var(--runway-input);color:var(--runway-ink)}.pl-inline button,.pl-move button{font-size:11px;padding:5px;color:var(--runway-accent)}.pl-export-all{display:flex;align-items:center;gap:8px;padding:16px;font-size:11px;color:var(--runway-accent)}
</style>
