package test

import (
	"net/http"
)

func (p *localControlPanel) handler() http.Handler {
	mux := http.NewServeMux()
	mux.HandleFunc("/", p.handleIndex)
	p.registerSetupEditorHandlers(mux)
	mux.HandleFunc("/static/", p.handleControlPanelStaticAsset)
	mux.HandleFunc("/api/preflight", p.handlePreflight)
	mux.HandleFunc("/api/state", p.handleState)
	mux.HandleFunc("/api/clusters/details", p.handleClusterDeploymentDetails)
	mux.HandleFunc("/api/images/search", p.handleImageLookupSearch)
	mux.HandleFunc("/api/images/inspect", p.handleImageLookupInspect)
	mux.HandleFunc("/api/images/build-yaml/source", p.handleImageLookupSourceBuildYAML)
	mux.HandleFunc("/api/pr-builds/verify", p.handlePRBuildVerify)
	mux.HandleFunc("/api/logs", p.handleLogs)
	mux.HandleFunc("/api/logs/stream", p.handleLogStream)
	mux.HandleFunc("/api/docker-logs", p.handleDockerLogs)
	mux.HandleFunc("/api/kubeconfig", p.handleKubeconfigDownload)
	mux.HandleFunc("/api/kubeconfig/save", p.handleKubeconfigSave)
	mux.HandleFunc("/api/helm-command", p.handleHelmCommandDownload)
	mux.HandleFunc("/api/helm-lab/save", p.handleHelmLabSave)
	mux.HandleFunc("/api/helm-lab/catalog", p.handleHelmLabCatalog)
	mux.HandleFunc("/api/release-trackers", p.handleReleaseTrackers)
	mux.HandleFunc("/api/my-work", p.handleMyWork)
	mux.HandleFunc("/api/my-work/refresh", p.handleRefreshMyWork)
	mux.HandleFunc("/api/issue-readiness", p.handleIssueReadiness)
	mux.HandleFunc("/api/issue-readiness/daily", p.handleDailyReadiness)
	mux.HandleFunc("/api/issue-radar", p.handleIssueRadar)
	mux.HandleFunc("/api/issue-radar/milestones", p.handleIssueRadarMilestones)
	mux.HandleFunc("/api/issue-radar/history", p.handleIssueRadarHistory)
	mux.HandleFunc("/api/issue-radar/save", p.handleIssueRadarSave)
	mux.HandleFunc("/api/open-url", p.handleOpenURL)
	mux.HandleFunc("/api/open-path", p.handleOpenPath)
	mux.HandleFunc("/api/setup", p.handleSetup)
	mux.HandleFunc("/api/run-slots/start", p.handleRunSlotStart)
	mux.HandleFunc("/api/operations/abort", p.handleAbortOperation)
	mux.HandleFunc("/api/test-lab", p.handleTestLab)
	mux.HandleFunc("/api/issue-packages", p.handleIssuePackages)
	mux.HandleFunc("/api/rancher/targets", p.handleRancherTargets)
	mux.HandleFunc("/api/rancher/operations", p.handleRancherOperations)
	mux.HandleFunc("/api/cluster-workspaces", p.handleClusterWorkspaces)
	mux.HandleFunc("/api/cluster-history", p.handleClusterHistory)
	mux.HandleFunc("/api/rancher/token", p.handleRancherToken)
	mux.HandleFunc("/api/cache-lab", p.handleCacheLab)
	mux.HandleFunc("/api/cache-lab/import", p.handleCacheLab)
	mux.HandleFunc("/api/steve/state", p.handleSteveLabState)
	mux.HandleFunc("/api/steve/versions", p.handleSteveLabVersions)
	mux.HandleFunc("/api/steve/ref", p.handleSteveLabRef)
	mux.HandleFunc("/api/steve/start", p.handleSteveLabStart)
	mux.HandleFunc("/api/steve/stop", p.handleSteveLabStop)
	mux.HandleFunc("/api/steve/cleanup", p.handleSteveLabCleanup)
	mux.HandleFunc("/api/steve/kubeconfig/save", p.handleSteveLabKubeconfigSave)
	mux.HandleFunc("/api/steve/sqlite/vacuum", p.handleSteveLabSqliteVacuum)
	mux.HandleFunc("/api/steve/logs", p.handleSteveLabLogs)
	mux.HandleFunc("/api/steve/output/clear", p.handleSteveLabOutputClear)
	mux.HandleFunc("/api/k3d/state", p.handleK3DLabState)
	mux.HandleFunc("/api/k3d/install", p.handleK3DLabInstall)
	mux.HandleFunc("/api/k3d/start", p.handleK3DLabStart)
	mux.HandleFunc("/api/k3d/stop", p.handleK3DLabStop)
	mux.HandleFunc("/api/k3d/restart", p.handleK3DLabRestart)
	mux.HandleFunc("/api/k3d/delete", p.handleK3DLabDelete)
	mux.HandleFunc("/api/k3d/kubeconfig/save", p.handleK3DLabKubeconfigSave)
	mux.HandleFunc("/api/k3d/output/clear", p.handleK3DLabOutputClear)
	mux.HandleFunc("/api/readiness", p.handleReadiness)
	mux.HandleFunc("/api/downstream/retry", p.handleDownstreamRetry)
	mux.HandleFunc("/api/cleanup", p.handleCleanup)
	mux.HandleFunc("/api/linode/inventory", p.handleLinodeInventory)
	mux.HandleFunc("/api/aws/cleanup/preview", p.handleAWSCleanupPreview)
	mux.HandleFunc("/api/aws/cleanup", p.handleAWSCleanup)
	mux.HandleFunc("/api/costs/reset", p.handleCostLedgerReset)
	mux.HandleFunc("/api/costs/transfer", p.handleCostTransfer)
	mux.HandleFunc("/api/local-artifacts/clean", p.handleLocalArtifactsClean)
	mux.HandleFunc("/api/shutdown", p.handleShutdown)
	return mux
}
